'use strict';
const assert=require('assert'),fs=require('fs'),net=require('net'),os=require('os'),path=require('path');
const app=require('../server');
const sslMonitor=require('../ssl-monitor');
const smtpMonitor=require('../smtp');
const dnsTools=require('../dns-tools');
const networkTools=require('../network-tools');
async function run(){
  assert.deepStrictEqual(app.assignments('example.com=s1|s2;example.net=google'),{'example.com':['s1','s2'],'example.net':['google']});
  process.env.MONITORED_DOMAINS='example.com,example.net';
  process.env.DKIM_SELECTORS='example.com=s1|s2;example.net=google';
  process.env.TLS_ENDPOINTS='example.com=mta-sts.example.com:443|mail.example.com:465';
  process.env.OPENSEARCH_PASSWORD='test-only';
  const config=app.envConfig();
  assert.strictEqual(config.domains.length,2);
  assert.deepStrictEqual(config.domains[0].dkim_selectors,['s1','s2']);
  assert.deepStrictEqual(config.domains[0].tls_endpoints,[{host:'mta-sts.example.com',port:443},{host:'mail.example.com',port:465}]);
  const settings=app.normalizeSettings({monitored_domains:['Example.com'],dkim_selectors:{'example.com':['s1','s2']},tls_endpoints:{'example.com':[{host:'mail.example.com',port:465}]},smtp_profiles:{'example.com':{hosting_type:'self_hosted',provider:'auto',expected_hostname:'mail.example.com',relay_context:'external'}},smtp_probe_hostname:'probe.example.com',report_days:14,refresh_minutes:30,request_timeout_ms:5000,report_source:'standalone',opensearch_url:'http://parsedmarc-opensearch:9200',mailbox:{enabled:true,host:'imap.example.com',port:993,username:'reports@example.com',reports_folder:'INBOX',archive_folder:'Archive'},snapshots:{enabled:true,cron:'0 2 * * *',delete_cron:'30 2 * * *',timezone:'UTC',retention_days:30,min_count:7,max_count:60}});
  assert.deepStrictEqual(settings.monitored_domains,['example.com']);
  assert.strictEqual(settings.opensearch_enabled,true);
  assert.strictEqual(settings.report_source,'standalone');
  assert.strictEqual(settings.schema_version,11);
  assert.deepStrictEqual(settings.check_sections['example.com'],{domain_certificates:true,additional_tls:true,smtp:true,dkim:true,mail_security:true,bimi:true});
  assert.deepStrictEqual(settings.certificate_checks['example.com'],{check_public:true,check_origin:false,origin_ip:''});
  assert.strictEqual(settings.certificate_check_minutes,360);
  assert.strictEqual(settings.smtp_probe_cooldown_minutes,30);
  assert.strictEqual(app.settingsConfig(settings).smtp_probe_cooldown_minutes,30);
  assert.strictEqual(settings.dns_change_confirmations,2);
  assert.strictEqual(settings.dns_monitoring_enabled['example.com'],false);
  assert.deepStrictEqual(settings.dns_monitors['example.com'],[]);
  assert.strictEqual(settings.notifications.dns_changes_enabled,true);
  assert.strictEqual(settings.notifications.ssl_warning_threshold,30);
  const discordUrl='https://discord.com/api/webhooks/123456789/test-token_value';
  assert.strictEqual(app.validDiscordWebhookUrl(discordUrl).toString(),discordUrl);
  assert.strictEqual(app.validDiscordWebhookUrl('http://discord.com/api/webhooks/123/token'),null);
  assert.strictEqual(app.validDiscordWebhookUrl('https://discord.example/api/webhooks/123/token'),null);
  assert.strictEqual(app.validDiscordWebhookUrl(`${discordUrl}?wait=true`),null);
  process.env.DOMAINPOSTURE_DISCORD_WEBHOOK='https://discord.com/api/webhooks/222/environment-token';
  assert.strictEqual(app.discordWebhookConfiguration({}).source,'environment');
  const savedDiscord=app.discordWebhookConfiguration({discord_webhook:discordUrl});
  assert.strictEqual(savedDiscord.source,'settings');
  assert.strictEqual(savedDiscord.url.toString(),discordUrl);
  let testedDiscordMessage='';
  let testedDiscordWebhook=null;
  const discordTest=await app.testDiscordNotification(async(message,webhook)=>{testedDiscordMessage=message;testedDiscordWebhook=webhook;return true;},savedDiscord.url);
  assert.strictEqual(discordTest.ok,true);
  assert.match(testedDiscordMessage,/Test Notification/);
  assert.strictEqual(testedDiscordWebhook.toString(),discordUrl);
  await assert.rejects(()=>app.testDiscordNotification(async()=>true,null),/Configure and save/);
  await assert.rejects(()=>app.testDiscordNotification(async()=>false,savedDiscord.url),/did not accept/);
  delete process.env.DOMAINPOSTURE_DISCORD_WEBHOOK;
  const secretsKey=Buffer.alloc(32,7);
  const encryptedSecrets=app.encryptSecrets({discord_webhook:discordUrl,imap_password:'private'},secretsKey);
  assert.strictEqual(app.encryptedSecretsDocument(encryptedSecrets),true);
  assert.doesNotMatch(JSON.stringify(encryptedSecrets),/private|discord\.com/);
  assert.deepStrictEqual(app.decryptSecrets(encryptedSecrets,secretsKey),{discord_webhook:discordUrl,imap_password:'private'});
  assert.throws(()=>app.decryptSecrets(encryptedSecrets,Buffer.alloc(32,8)),/original key/);
  assert.deepStrictEqual(app.decodeSecretsKey(secretsKey.toString('base64')),secretsKey);
  assert.throws(()=>app.decodeSecretsKey('too-short'),/exactly 32 bytes/);
  const keyTestDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'domainposture-key-'));
  try {
    const managedKeyPath=path.join(keyTestDirectory,'.domainposture-secrets-key');
    const managedSecretsPath=path.join(keyTestDirectory,'secrets.json');
    fs.writeFileSync(managedSecretsPath,JSON.stringify({imap_password:'legacy-private'}),{mode:0o600});
    const generated=await app.createManagedSecretsKey({keyPath:managedKeyPath,secretsPath:managedSecretsPath,current:{key:null,source:null}});
    const generatedKey=app.decodeSecretsKey(generated.key);
    assert.strictEqual(generatedKey.length,32);
    assert.strictEqual(generated.source,'managed');
    assert.strictEqual(generated.migrated_legacy_secrets,true);
    assert.strictEqual(fs.statSync(managedKeyPath).mode&0o777,0o600);
    const migratedSecrets=JSON.parse(fs.readFileSync(managedSecretsPath,'utf8'));
    assert.strictEqual(app.encryptedSecretsDocument(migratedSecrets),true);
    assert.deepStrictEqual(app.decryptSecrets(migratedSecrets,generatedKey),{imap_password:'legacy-private'});
    const pendingKey=Buffer.alloc(32,9);
    const keyring=app.decodeManagedSecretsKeyFile(JSON.stringify({schema_version:1,current:pendingKey.toString('base64'),previous:[generated.key]}));
    assert.deepStrictEqual(app.decryptSecretsWithKeys(migratedSecrets,keyring.keys),{imap_password:'legacy-private'});
    await assert.rejects(()=>app.createManagedSecretsKey({keyPath:managedKeyPath,secretsPath:managedSecretsPath,current:{key:generatedKey,source:'managed'}}),/already configured/);
    await assert.rejects(()=>app.createManagedSecretsKey({keyPath:path.join(keyTestDirectory,'replacement-key'),secretsPath:managedSecretsPath,current:{key:null,source:null}}),/Restore the original key/);
    const rotated=await app.rotateManagedSecretsKey({keyPath:managedKeyPath,secretsPath:managedSecretsPath,current:{key:generatedKey,keys:[generatedKey],source:'managed'}});
    const rotatedKey=app.decodeSecretsKey(rotated.key);
    assert.notDeepStrictEqual(rotatedKey,generatedKey);
    assert.strictEqual(fs.readFileSync(managedKeyPath,'utf8').trim(),rotated.key);
    assert.deepStrictEqual(app.decryptSecrets(JSON.parse(fs.readFileSync(managedSecretsPath,'utf8')),rotatedKey),{imap_password:'legacy-private'});
    await assert.rejects(()=>app.rotateManagedSecretsKey({keyPath:managedKeyPath,secretsPath:managedSecretsPath,current:{key:rotatedKey,source:'external'}}),/Only an encryption key managed/);
  } finally {
    fs.rmSync(keyTestDirectory,{recursive:true,force:true});
  }
  const originSettings=app.normalizeSettings({monitored_domains:['example.com'],certificate_checks:{'example.com':{check_public:true,check_origin:true,origin_ip:'2001:db8::10'}}});
  assert.deepStrictEqual(originSettings.certificate_checks['example.com'],{check_public:true,check_origin:true,origin_ip:'2001:db8::10'});
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],certificate_checks:{'example.com':{check_public:false,check_origin:false}}}),/at least one certificate check/i);
  const certificateOnlySettings=app.normalizeSettings({monitored_domains:['example.com'],check_sections:{'example.com':{domain_certificates:true,additional_tls:false,smtp:false,dkim:false,mail_security:false,bimi:false}}});
  assert.deepStrictEqual(app.settingsConfig(certificateOnlySettings).domains[0].check_sections,{domain_certificates:true,additional_tls:false,smtp:false,dkim:false,mail_security:false,bimi:false});
  const certificatesOff=app.normalizeSettings({monitored_domains:['example.com'],check_sections:{'example.com':{domain_certificates:false}},certificate_checks:{'example.com':{check_public:false,check_origin:false}}});
  assert.strictEqual(certificatesOff.certificate_checks['example.com'].check_public,false);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],check_sections:{'example.com':{domain_certificates:false,additional_tls:false,smtp:false,dkim:false,mail_security:false,bimi:false}}}),/at least one check section/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],certificate_checks:{'example.com':{check_origin:true,origin_ip:'not an ip'}}}),/valid origin IPv4 or IPv6/i);
  assert.strictEqual(settings.smtp_probe_hostname,'probe.example.com');
  assert.deepStrictEqual(settings.smtp_profiles['example.com'],{hosting_type:'self_hosted',provider:'auto',expected_hostname:'mail.example.com',relay_context:'external'});
  assert.strictEqual(settings.mailbox.archive_folder,'Archive');
  assert.strictEqual(settings.parsedmarc.general.save_smtp_tls,true);
  assert.strictEqual(settings.parsedmarc.mailbox.delete_smtp_tls,false);
  assert.strictEqual(settings.parsedmarc.opensearch.number_of_replicas,0);
  assert.strictEqual(settings.parsedmarc.opensearch.monthly_indexes,true);
  assert.strictEqual(app.normalizeSettings({parsedmarc:{mailbox:{batch_size:0}}}).parsedmarc.mailbox.batch_size,0);
  assert.strictEqual(settings.snapshots.cron,'0 2 * * *');
  const bimiSettings=app.normalizeSettings({monitored_domains:['example.com'],bimi_exceptions:{'example.com':{mode:'permanent'},'other.example':{mode:'permanent'}}});
  assert.deepStrictEqual(bimiSettings.bimi_exceptions,{'example.com':{self_asserted:{mode:'permanent'}}});
  assert.deepStrictEqual(app.settingsConfig(bimiSettings).domains[0].bimi_exception,{self_asserted:{mode:'permanent'}});
  const noLogoSettings=app.normalizeSettings({monitored_domains:['example.com'],bimi_exceptions:{'example.com':{no_logo:{mode:'permanent'}}}});
  assert.deepStrictEqual(noLogoSettings.bimi_exceptions,{'example.com':{no_logo:{mode:'permanent'}}});
  assert.strictEqual(app.activeBimiException({mode:'permanent'}).active,true);
  assert.strictEqual(app.activeBimiException({mode:'until',expires_at:'2099-01-01T00:00:00.000Z'},Date.parse('2026-01-01T00:00:00.000Z')).active,true);
  assert.strictEqual(app.activeBimiException({mode:'until',expires_at:'2025-01-01T00:00:00.000Z'},Date.parse('2026-01-01T00:00:00.000Z')).active,false);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],bimi_exceptions:{'example.com':{mode:'until',expires_at:'not-a-date'}}}),/Invalid BIMI .*exception expiration/);
  const controlSettings=app.normalizeSettings({monitored_domains:['example.com'],control_exceptions:{'example.com':{mta_sts:{mode:'permanent'},tls_certificates:{mode:'until',expires_at:'2099-01-01T00:00:00.000Z'}},'other.example':{mta_sts:{mode:'permanent'}}}});
  assert.deepStrictEqual(controlSettings.control_exceptions,{'example.com':{mta_sts:{mode:'permanent'},tls_certificates:{mode:'until',expires_at:'2099-01-01T00:00:00.000Z'}}});
  assert.deepStrictEqual(app.settingsConfig(controlSettings).domains[0].control_exception,controlSettings.control_exceptions['example.com']);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],control_exceptions:{'example.com':{mta_sts:{mode:'until',expires_at:'not-a-date'}}}}),/Invalid MTA-STS exception expiration/);
  const missingMta={id:'mta_sts',label:'MTA-STS',status:'critical',summary:'Not configured',detail:'No STSv1 DNS signal is published.',action:'Publish a policy.',evidence:{raw_dns:[],dns:[]}};
  assert.strictEqual(app.isMissingMtaSts(missingMta),true);
  assert.strictEqual(app.isMissingMtaSts({...missingMta,evidence:{raw_dns:['invalid policy'],dns:[]}}),false);
  const ignoredMta=app.applyMissingControlException(missingMta,{mode:'permanent'},'mta_sts_absent');
  assert.strictEqual(ignoredMta.status,'ignored');
  assert.strictEqual(ignoredMta.evidence.original_status,'critical');
  assert.strictEqual(ignoredMta.evidence.ignore_reason,'mta_sts_absent');
  assert.strictEqual(app.applyMissingControlException(missingMta,{mode:'until',expires_at:'2025-01-01T00:00:00.000Z'}).status,'critical');
  const ignoredSummary=app.summarize('example.com',[{status:'healthy'},{status:'ignored'}]);
  assert.strictEqual(ignoredSummary.status,'healthy');
  assert.strictEqual(ignoredSummary.counts.ignored,1);
  process.env.OPENSEARCH_VERIFY_TLS='true';
  assert.strictEqual(app.normalizeSettings({monitored_domains:['example.com']}).opensearch_verify_tls,true);
  delete process.env.OPENSEARCH_VERIFY_TLS;
  assert.strictEqual(app.settingsConfig(settings).domains[0].report_days,14);
  assert.strictEqual(app.settingsConfig(settings).domains[0].smtp_profile.hosting_type,'self_hosted');
  assert.strictEqual(app.normalizeSettings({monitored_domains:['example.com'],smtp_profiles:{'example.com':{hosting_type:'self_hosted',provider:'kerio'}}}).smtp_profiles['example.com'].provider,'kerio');
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],smtp_probe_hostname:'not-a-host'}),/fully qualified/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],smtp_probe_cooldown_minutes:4}),/SMTP probe cooldown/);
  const dnsMonitorSettings=app.normalizeSettings({monitored_domains:['example.com'],dns_change_confirmations:3,dns_monitoring_enabled:{'example.com':true},dns_monitors:{'example.com':[{host:'WWW.Example.com.',type:'a'},{host:'www.example.com',type:'A'},{host:'example.com',type:'SOA'}]}});
  assert.deepStrictEqual(dnsMonitorSettings.dns_monitors['example.com'],[{host:'www.example.com',type:'A'},{host:'example.com',type:'SOA'}]);
  assert.strictEqual(dnsMonitorSettings.dns_monitoring_enabled['example.com'],true);
  assert.strictEqual(app.settingsConfig(dnsMonitorSettings).dns_change_confirmations,3);
  assert.strictEqual(app.settingsConfig(dnsMonitorSettings).domains[0].dns_monitoring_enabled,true);
  assert.deepStrictEqual(app.settingsConfig(dnsMonitorSettings).domains[0].dns_monitors,dnsMonitorSettings.dns_monitors['example.com']);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],dns_monitoring_enabled:{'example.com':true}}),/at least one DNS record/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],dns_monitors:{'example.com':[{host:'bad host',type:'A'}]}}),/Invalid DNS monitoring host/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],dns_monitors:{'example.com':[{host:'example.com',type:'ANY'}]}}),/Invalid DNS monitoring record type/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],smtp_profiles:{'example.com':{expected_hostname:'bad host'}}}),/expected SMTP hostname/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['not a domain']}),/Invalid monitored domain/);
  assert.strictEqual(app.sameOriginRequest({headers:{host:'domainposture.example',origin:'https://domainposture.example'}}),true);
  assert.strictEqual(app.sameOriginRequest({headers:{host:'domainposture.example',origin:'https://other.example'}}),false);
  assert.deepStrictEqual(sslMonitor.sslWatchArguments({domain:'example.com',checkType:'public',timeoutMs:5000}),['-domain','example.com','-port','443','-output','json','-fingerprint','-timeout','5']);
  assert.deepStrictEqual(sslMonitor.sslWatchArguments({domain:'example.com',checkType:'origin',originIp:'192.0.2.10',timeoutMs:5000}),['-domain','example.com','-port','443','-ipaddr','192.0.2.10','-servername','example.com','-output','json','-fingerprint','-timeout','5']);
  assert.throws(()=>sslMonitor.sslWatchArguments({domain:'example.com;touch /tmp/pwned',checkType:'public'}),/valid domain/);
  assert.throws(()=>sslMonitor.sslWatchArguments({domain:'example.com',checkType:'origin',originIp:'127.0.0.1 --insecure'}),/valid IPv4 or IPv6/);
  const sslJson={fingerprint:'public-fingerprint',common_name:'example.com',subject:'CN=example.com',issuer:'CN=Example CA',sans:['example.com'],not_before:'2026-09-01T00:00:00Z',not_after:'2026-12-01T00:00:00Z',days_remaining:56,used_ip:'203.0.113.10',tls_version:'TLS 1.3',cipher_suite:'TLS_AES_128_GCM_SHA256',chain_valid:true};
  const publicCertificate=await sslMonitor.runCertificateCheck({domain:'example.com',checkType:'public',checkedAt:'2026-10-05T00:00:00Z',execute:async()=>JSON.stringify(sslJson)});
  const originCertificate=await sslMonitor.runCertificateCheck({domain:'example.com',checkType:'origin',originIp:'192.0.2.10',checkedAt:'2026-10-05T00:00:00Z',execute:async()=>JSON.stringify({...sslJson,fingerprint:'origin-fingerprint',issuer:'CN=Origin CA',used_ip:'192.0.2.10'})});
  assert.strictEqual(publicCertificate.status,'good');
  assert.strictEqual(originCertificate.ip_used,'192.0.2.10');
  assert.notStrictEqual(publicCertificate.fingerprint,originCertificate.fingerprint);
  const certificateComponent=sslMonitor.componentResult('example.com',[publicCertificate,{...originCertificate,status:'urgent',status_label:'Urgent',score_credit:.55,days_remaining:10}]);
  assert.strictEqual(certificateComponent.status,'warning');
  assert.strictEqual(certificateComponent.evidence.score_credit,.55);
  assert.strictEqual(app.domainScore(Array(10).fill({status:'healthy'}).concat(certificateComponent)),96);
  assert.strictEqual(app.domainScore(Array(10).fill({status:'healthy'}).concat({...certificateComponent,status:'critical',evidence:{...certificateComponent.evidence,score_credit:0}})),91);
  const publicOnlyComponent=sslMonitor.componentResult('example.com',[publicCertificate]);
  assert.strictEqual(publicOnlyComponent.evidence.origin,null);
  assert.strictEqual(app.domainScore(Array(10).fill({status:'healthy'}).concat(publicOnlyComponent)),100,'a disabled origin path must not affect the score');
  assert.strictEqual(app.domainScore([{...certificateComponent,status:'warning',evidence:{...certificateComponent.evidence,score_credit:.55}}]),55,'the certificate component must be the entire score when every other section is disabled');
  assert.strictEqual(sslMonitor.certificateState({...sslJson,days_remaining:29}), 'needs_attention');
  assert.strictEqual(sslMonitor.certificateState({...sslJson,days_remaining:14}), 'urgent');
  assert.strictEqual(sslMonitor.certificateState({...sslJson,days_remaining:7}), 'critical');
  assert.strictEqual(sslMonitor.certificateState({...sslJson,days_remaining:-1}), 'expired');
  assert.strictEqual(sslMonitor.certificateState({...sslJson,chain_valid:false}), 'invalid');
  assert.strictEqual(sslMonitor.milestoneFor({...publicCertificate,days_remaining:29,status:'needs_attention'},[30,14,7]),30);
  const failedCertificate=await sslMonitor.runCertificateCheck({domain:'example.com',checkType:'public',previous:publicCertificate,execute:async()=>'{bad json'});
  assert.strictEqual(failedCertificate.status,'check_failed');
  assert.strictEqual(failedCertificate.last_successful_check,publicCertificate.last_successful_check);
  for(const executionError of [Object.assign(new Error('lookup example.com: no such host'),{code:'ENOTFOUND'}),Object.assign(new Error('connect: connection refused'),{code:'ECONNREFUSED'})]){
    const unavailable=await sslMonitor.runCertificateCheck({domain:'example.com',checkType:'public',execute:async()=>{throw executionError;}});
    assert.strictEqual(unavailable.status,'check_failed');
    assert.match(unavailable.error,/host|refused/);
  }
  const mismatch=await sslMonitor.runCertificateCheck({domain:'example.com',checkType:'origin',originIp:'192.0.2.10',execute:async()=>JSON.stringify({...sslJson,chain_valid:true,name_mismatch:true})});
  assert.strictEqual(mismatch.status,'invalid');
  const cacheDomain=`cache-${Date.now()}.example.com`;
  const cacheEntry={domain:cacheDomain,certificate_checks:{check_public:true,check_origin:true,origin_ip:'192.0.2.20'}};
  const cacheConfig={certificate_check_minutes:360,notifications:{ssl_warning_threshold:30}};
  let certificateExecutions=0;
  const cacheExecute=async(_binary,args)=>{
    certificateExecutions+=1;
    const origin=args.includes('-ipaddr');
    return JSON.stringify({...sslJson,fingerprint:origin?'cache-origin':'cache-public',used_ip:origin?'192.0.2.20':'203.0.113.20'});
  };
  const firstCertificateComponent=await app.domainCertificateComponent(cacheEntry,cacheConfig,{execute:cacheExecute});
  assert.strictEqual(certificateExecutions,2);
  assert.notStrictEqual(firstCertificateComponent.evidence.public.fingerprint,firstCertificateComponent.evidence.origin.fingerprint);
  await app.domainCertificateComponent(cacheEntry,cacheConfig,{execute:cacheExecute});
  assert.strictEqual(certificateExecutions,2,'fresh certificate results should be served from the cache');
  await app.domainCertificateComponent(cacheEntry,cacheConfig,{execute:cacheExecute,forceCertificates:true});
  assert.strictEqual(certificateExecutions,4,'manual checks should force both enabled certificate paths');
  const notificationState={certificates:{},domains:{}};
  const sentNotifications=[];
  const notificationSettings={discord_enabled:true,ssl_enabled:true,needs_attention_enabled:true,ssl_milestones:[30,14,7]};
  const notify=content=>{sentNotifications.push(content);return Promise.resolve(true);};
  const notificationResult=(certificate,status='healthy',score=100)=>({domain:'notify.example.com',status,score,checks:[sslMonitor.componentResult('notify.example.com',[certificate])]});
  await app.processNotifications(notificationResult(publicCertificate),notificationSettings,notify,{state:notificationState,webhookReady:true});
  assert.strictEqual(sentNotifications.length,0,'initial state should establish a baseline without alerting');
  const atThirty={...publicCertificate,status:'needs_attention',status_label:'Needs attention',score_credit:.8,days_remaining:29,checked_at:'2026-10-06T00:00:00Z'};
  await app.processNotifications(notificationResult(atThirty,'warning',98),notificationSettings,notify,{state:notificationState,webhookReady:true});
  assert.strictEqual(sentNotifications.length,2,'certificate and domain transitions should each notify once');
  assert.match(sentNotifications[0],/SSL Certificate Expiring Soon/);
  assert.match(sentNotifications[1],/Domain Needs Attention/);
  await app.processNotifications(notificationResult({...atThirty,days_remaining:28,checked_at:'2026-10-07T00:00:00Z'},'warning',98),notificationSettings,notify,{state:notificationState,webhookReady:true});
  assert.strictEqual(sentNotifications.length,2,'unchanged actionable state should not generate duplicates');
  const atFourteen={...atThirty,status:'urgent',status_label:'Urgent',score_credit:.55,days_remaining:14,checked_at:'2026-10-21T00:00:00Z'};
  await app.processNotifications(notificationResult(atFourteen,'warning',96),notificationSettings,notify,{state:notificationState,webhookReady:true});
  assert.strictEqual(sentNotifications.length,3,'crossing the next milestone should notify once');
  const recovered={...publicCertificate,fingerprint:'renewed-fingerprint',days_remaining:90,checked_at:'2026-10-22T00:00:00Z'};
  await app.processNotifications(notificationResult(recovered),notificationSettings,notify,{state:notificationState,webhookReady:true});
  assert.strictEqual(sentNotifications.length,5,'certificate and domain recovery should each notify once');
  assert.match(sentNotifications[3],/SSL Certificate Recovered/);
  assert.match(sentNotifications[4],/Domain Recovered/);
  const dnsNotificationState={dns_records:{}};const dnsNotifications=[];
  const dnsNotificationSettings={discord_enabled:true,dns_changes_enabled:true,dns_change_confirmations:2};
  const dnsObservation=identity=>({domain:'example.com',reports:{dns_monitoring:{records:[{host:'www.example.com',type:'A',status:'available',identity,values:identity,checked_at:'2026-10-06T00:00:00Z'}]}}});
  const dnsSend=message=>{dnsNotifications.push(message);return Promise.resolve(true);};
  const dnsBaseline=dnsObservation(['192.0.2.10']);
  await app.processDnsChangeNotifications(dnsBaseline,dnsNotificationSettings,dnsSend,{state:dnsNotificationState,webhookReady:true});
  assert.strictEqual(dnsBaseline.reports.dns_monitoring.records[0].change_state,'baseline');
  const dnsPending=dnsObservation(['192.0.2.20']);
  await app.processDnsChangeNotifications(dnsPending,dnsNotificationSettings,dnsSend,{state:dnsNotificationState,webhookReady:true});
  assert.strictEqual(dnsPending.reports.dns_monitoring.records[0].change_state,'pending');
  assert.strictEqual(dnsNotifications.length,0);
  const dnsChanged=dnsObservation(['192.0.2.20']);
  await app.processDnsChangeNotifications(dnsChanged,dnsNotificationSettings,dnsSend,{state:dnsNotificationState,webhookReady:true});
  assert.strictEqual(dnsChanged.reports.dns_monitoring.records[0].change_state,'changed');
  assert.strictEqual(dnsNotifications.length,1);
  assert.match(dnsNotifications[0],/DNS Record Changed/);
  assert.match(dnsNotifications[0],/Previous: 192\.0\.2\.10/);
  assert.match(dnsNotifications[0],/Current: 192\.0\.2\.20/);
  assert.throws(()=>app.normalizeSettings({snapshots:{cron:'not cron'}}),/five-field cron/);
  assert.strictEqual(app.validCron('0 2 * * *'),true);
  assert.strictEqual(app.validCron('0 2 * *'),false);
  assert.strictEqual(app.validCron('99 2 * * *'),false);
  process.env.OPENSEARCH_PASSWORD='open%search';
  const ini=app.parsedmarcIni(settings,{imap_password:'test%secret'});
  assert.match(ini,/reports_folder = INBOX/);
  assert.match(ini,/archive_folder = Archive/);
  assert.match(ini,/password = test%%secret/);
  assert.match(ini,/password = open%%search/);
  assert.match(ini,/save_smtp_tls = True/);
  assert.match(ini,/delete_smtp_tls = False/);
  assert.match(ini,/since = 1d/);
  assert.match(ini,/number_of_replicas = 0/);
  assert.strictEqual(app.parsedmarcConfigurationStatus(settings,ini).status,'healthy');
  assert.strictEqual(app.parsedmarcConfigurationStatus({...settings,mailbox:{...settings.mailbox,enabled:false}},'').status,'warning');
  assert.strictEqual(app.parsedmarcConfigurationStatus(settings,'[general]\n[imap]\n').status,'critical');
  assert.strictEqual(app.overallStatus([{status:'healthy'},{status:'warning'}]),'warning');
  assert.strictEqual(app.overallStatus([{status:'warning'},{status:'critical'}]),'critical');
  assert.ok(Array.isArray(app.diagnosticLog().events));
  assert.strictEqual(app.redactLogText('password="private-value" token=abc123'),'password="[REDACTED]" token=[REDACTED]');
  assert.throws(()=>app.normalizeSettings({parsedmarc:{mailbox:{since:'yesterday'}}}),/number followed by/);
  const smtp=app.summarizeSmtpHits([{_source:{organization_name:'Sender',date_begin:'2026-09-01T00:00:00Z',policies:[{policy_domain:'example.com',successful_session_count:20,failed_session_count:2,failure_details:[{result_type:'validation-failure',failed_session_count:2}]}]}}],'example.com',7);
  assert.strictEqual(smtp.successful,20);
  assert.strictEqual(smtp.failed,2);
  assert.strictEqual(smtp.failure_types[0].type,'validation-failure');
  assert.strictEqual(smtp.raw_samples[0].organization_name,'Sender');
  assert.strictEqual(app.smtpOrganization({report_metadata:{organization_name:'Legacy Sender'}}),'Legacy Sender');
  assert.strictEqual(app.smtpOrganization({}, {organization_name:['Field Sender']}),'Field Sender');
  assert.strictEqual(app.smtpOrganization({}, {}),'Reporter name not provided');
  const dmarcReporters=app.summarizeDmarcReporters([{_source:{org_name:'Receiver',org_email:'reports@receiver.example',report_id:'one',date_end:'2026-09-02T00:00:00Z',message_count:4}},{_source:{org_name:'Receiver',org_email:'reports@receiver.example',report_id:'one',date_end:'2026-09-02T00:00:00Z',message_count:6}},{_source:{org_name:'Receiver',org_email:'reports@receiver.example',report_id:'two',date_end:'2026-09-03T00:00:00Z',message_count:2}}]);
  assert.strictEqual(dmarcReporters[0].domain,'receiver.example');
  assert.strictEqual(dmarcReporters[0].reports,2);
  assert.strictEqual(dmarcReporters[0].messages,12);
  const scopedSmtp=app.summarizeSmtpHits([{_index:'smtp_tls-1',_source:{organization_name:'Other',policies:[{policy_domain:'other.example',successful_session_count:1}]}},{_index:'smtp_tls-1',_source:{organization_name:'Ours',policies:[{policy_domain:'example.com',successful_session_count:2}]}}],'example.com',7);
  assert.strictEqual(scopedSmtp.raw_samples.length,1);
  assert.strictEqual(scopedSmtp.raw_samples[0].organization_name,'Ours');
  const attributedSmtp=app.summarizeSmtpHits([{_source:{organization_name:'Sender',contact_info:'mailto:tls-reports@sender.example',policies:[{policy_domain:'example.com',successful_session_count:3}]}}],'example.com',7);
  assert.deepStrictEqual(attributedSmtp.organizations[0].domains,['sender.example']);
  assert.strictEqual(app.mxMatch('mx1.example.com','*.example.com'),true);
  assert.strictEqual(app.smtpBannerHostname(['220 mail.example.com ESMTP ready']),'mail.example.com');
  assert.deepStrictEqual(app.smtpCapabilities(['250-mail.example.com','250-PIPELINING','250 STARTTLS']),['MAIL.EXAMPLE.COM','PIPELINING','STARTTLS']);
  assert.strictEqual(app.validSmtpHostname('mail.example.com'),true);
  assert.strictEqual(app.validSmtpHostname('localhost'),false);
  const hoverProfile=app.smtpProfile('seal.fyi',{hosting_type:'auto',provider:'auto'},[{exchange:'mx.hover.com.cust.hostedemail.com'}]);
  assert.strictEqual(hoverProfile.hosting_type,'managed');
  assert.strictEqual(hoverProfile.provider,'hover');
  assert.strictEqual(hoverProfile.provider_label,'Hover Mail');
  assert.strictEqual(hoverProfile.hosting_source,'auto_detected');
  assert.strictEqual(hoverProfile.provider_source,'auto_detected');
  const icloudProfile=app.smtpProfile('macsupportla.com',{hosting_type:'auto',provider:'auto'},[{exchange:'mx01.mail.icloud.com'},{exchange:'mx02.mail.icloud.com'}]);
  assert.strictEqual(icloudProfile.hosting_type,'managed');
  assert.strictEqual(icloudProfile.provider,'icloud');
  assert.strictEqual(icloudProfile.provider_label,'iCloud Mail');
  const kerioProfile=app.smtpProfile('sealsystems.net',{hosting_type:'auto',provider:'kerio'},[{exchange:'mail.sealsystems.net'}]);
  assert.strictEqual(kerioProfile.hosting_type,'self_hosted');
  assert.strictEqual(kerioProfile.provider,'kerio');
  assert.strictEqual(kerioProfile.provider_label,'Kerio Connect');
  assert.strictEqual(kerioProfile.hosting_source,'selected');
  assert.strictEqual(kerioProfile.provider_source,'selected');
  const spfResolver={resolveTxt:async name=>name==='example.com'?[['v=spf1 include:_spf.example.net -all']]:[['v=spf1 ip4:192.0.2.0/24 -all']]};
  const spf=await app.spfCheck('example.com',{resolver:spfResolver});
  assert.strictEqual(spf.status,'healthy');
  assert.strictEqual(spf.evidence.dns_lookup_terms,1);
  const softSpf=await app.spfCheck('example.com',{resolver:{resolveTxt:async()=>[['v=spf1 ~all']]}});
  assert.strictEqual(softSpf.status,'warning');
  const hoverSoftSpf=await app.spfCheck('example.com',{mail_profile:hoverProfile,resolver:{resolveTxt:async()=>[['v=spf1 ~all']]}});
  assert.strictEqual(hoverSoftSpf.status,'info');
  assert.match(hoverSoftSpf.action,/Hover-provided/);
  const unsafeSpf=await app.spfCheck('example.com',{resolver:{resolveTxt:async()=>[['v=spf1 +all']]}});
  assert.strictEqual(unsafeSpf.status,'critical');
  const invalidSpf=await app.spfCheck('example.com',{resolver:{resolveTxt:async()=>[['v=spf1 ip4:192.0.2.1/33 -all']]}});
  assert.strictEqual(invalidSpf.status,'critical');
  const timeoutStarted=Date.now();
  const timedOutSpf=await app.spfCheck('example.com',{timeout_ms:20,resolver:{resolveTxt:()=>new Promise(()=>{})}});
  assert.strictEqual(timedOutSpf.status,'warning');
  assert.strictEqual(timedOutSpf.summary,'DNS check unavailable');
  assert.ok(Date.now()-timeoutStarted<500,'SPF validation must respect its timeout');
  const tlsRpt=app.validateTlsRptRecord('v=TLSRPTv1; rua=mailto:tls@example.com,https://reports.example.net/v1/tlsrpt');
  assert.strictEqual(tlsRpt.valid,true);
  assert.strictEqual(tlsRpt.destinations.length,2);
  assert.strictEqual(app.validateTlsRptRecord('v=TLSRPTv1; rua=ftp://example.com/report').valid,false);
  assert.strictEqual(dnsTools.isPublicIp('8.8.8.8'),true);
  assert.strictEqual(dnsTools.isPublicIp('192.168.1.1'),false);
  assert.strictEqual(dnsTools.isPublicIp('2001:db8::1'),false);
  assert.strictEqual(dnsTools.isPublicIp('::ffff:192.168.1.1'),false);
  assert.strictEqual(dnsTools.isPublicIp('ff02::1'),false);
  assert.strictEqual(dnsTools.validSrvName('_sip._tcp.example.com'),true);
  assert.strictEqual(dnsTools.normalizeLookupTarget('_sip._tcp.example.com').kind,'srv');
  assert.strictEqual(dnsTools.normalizeLookupTool('dnssec'),'dnssec');
  assert.throws(()=>dnsTools.normalizeLookupTool('traceroute'),/supported Lookup Center tool/);
  const dnsA=await dnsTools.resolveRecord('www.example.com','A',{resolver:{resolve4:async()=>[{address:'203.0.113.20',ttl:300}]}});
  assert.strictEqual(dnsA.status,'available');
  assert.deepStrictEqual(dnsA.identity,['203.0.113.20']);
  assert.deepStrictEqual(dnsTools.canonicalValues('A',[{address:'203.0.113.20',ttl:30},{address:'203.0.113.10',ttl:60}]),['203.0.113.10','203.0.113.20'],'DNS identity must ignore TTL and answer order');
  const dnsSoa=await dnsTools.resolveRecord('example.com','SOA',{resolver:{resolveSoa:async()=>({nsname:'ns1.example.net',hostmaster:'hostmaster.example.com',serial:2026100601,refresh:3600,retry:600,expire:1209600,minttl:300})}});
  assert.strictEqual(dnsSoa.values[0].serial,2026100601);
  assert.deepStrictEqual(dnsSoa.identity,['2026100601']);
  const dnsTlsRpt=await dnsTools.resolveRecord('example.com','TLSRPT',{resolver:{resolveTxt:async name=>{assert.strictEqual(name,'_smtp._tls.example.com');return [['v=TLSRPTv1; rua=mailto:tls@example.com']];}}});
  assert.deepStrictEqual(dnsTlsRpt.values,['v=TLSRPTv1; rua=mailto:tls@example.com']);
  const dnsSrv=await dnsTools.resolveRecord('_sip._tcp.example.com','SRV',{resolver:{resolveSrv:async()=>[{priority:10,weight:5,port:5060,name:'sip.example.com.'}]}});
  assert.deepStrictEqual(dnsSrv.values,[{priority:10,weight:5,port:5060,name:'sip.example.com'}]);
  const dnssec=await networkTools.dnssecCheck('example.com',{requestJson:async url=>{
    const type=url.searchParams.get('type');
    if(type==='SOA')return {Status:0,AD:true,Answer:[]};
    if(type==='DNSKEY')return {Status:0,AD:true,Answer:[{type:48,TTL:300,data:'257 3 13 public-key'}]};
    return {Status:0,AD:true,Answer:[{type:43,TTL:300,data:'12345 13 2 digest'}]};
  }});
  assert.strictEqual(dnssec.status,'healthy');
  assert.strictEqual(dnssec.evidence.dnskey.length,1);
  const registration=await networkTools.rdapRegistration('www.example.com',{requestJson:async url=>{
    if(url.hostname==='data.iana.org')return {services:[[['com'],['https://rdap.example.net/']]]};
    if(url.pathname.endsWith('/www.example.com'))throw Object.assign(new Error('not found'),{statusCode:404});
    return {url:url.toString(),body:{objectClassName:'domain',ldhName:'EXAMPLE.COM',handle:'TEST-1',status:['active'],events:[{eventAction:'registration',eventDate:'1995-01-01T00:00:00Z'},{eventAction:'expiration',eventDate:'2030-01-01T00:00:00Z'}],entities:[{roles:['registrar'],vcardArray:['vcard',[['fn',{},'text','Example Registrar']]]}],nameservers:[{ldhName:'NS1.EXAMPLE.COM'}]}};
  }});
  assert.strictEqual(registration.domain,'EXAMPLE.COM');
  assert.strictEqual(registration.registrar,'Example Registrar');
  assert.strictEqual(registration.expires_at,'2030-01-01T00:00:00Z');
  const ownership=await networkTools.asnOwnership(['8.8.8.8'],{resolver:{resolveTxt:async name=>name.startsWith('AS15169')?[['15169 | US | arin | 2000-03-30 | GOOGLE - Google LLC']]:[['15169 | 8.8.8.0/24 | US | arin | 1992-12-01']]}});
  assert.strictEqual(ownership.records[0].asn,'AS15169');
  assert.match(ownership.records[0].name,/GOOGLE/);
  const web=await networkTools.webDiagnostics('example.com',{webProbe:async url=>({status:'available',url:url.toString(),status_code:200,response_time_ms:20,redirects:[],headers:{strict_transport_security:'max-age=31536000'}})});
  assert.strictEqual(web.results.length,2);
  assert.strictEqual(web.status,'healthy');
  assert.strictEqual(networkTools.normalizeTcpPort(443),443);
  assert.throws(()=>networkTools.normalizeTcpPort(444),/allowed TCP port/);
  assert.deepStrictEqual(await networkTools.publicAddresses('public.example',{addressLookup:async()=>[{address:'2606:4700:4700::1111',family:6},{address:'8.8.8.8',family:4}]}),['8.8.8.8','2606:4700:4700::1111'],'IPv4 should be preferred on Docker hosts without IPv6 egress');
  const tcp=await networkTools.tcpPortCheck('example.com',443,{resolveAddresses:async()=>['8.8.8.8'],connectTcp:async({address,port})=>({status:'healthy',summary:`TCP ${port} is reachable`,detail:'Test connection.',address,port,response_time_ms:5})});
  assert.strictEqual(tcp.status,'healthy');
  const blockedTcp=await networkTools.tcpPortCheck('internal.example',443,{resolveAddresses:async()=>['192.168.1.10']});
  assert.match(blockedTcp.detail,/public address/);
  let lookupCalls=0,lookupNow=Date.parse('2026-10-06T12:00:00Z');
  const lookupCenter=dnsTools.createLookupCenter({ttl_ms:60000,now:()=>lookupNow,lookup:async target=>{lookupCalls+=1;return {target,checked_at:new Date(lookupNow).toISOString(),dns:[]};}});
  await Promise.all([lookupCenter.lookup('example.com'),lookupCenter.lookup('example.com')]);
  assert.strictEqual(lookupCalls,1,'simultaneous Lookup Center requests must be deduplicated');
  assert.strictEqual((await lookupCenter.lookup('example.com')).cached,true);
  assert.strictEqual(app.reverseIp('192.0.2.25'),'25.2.0.192');
  const missingDns=Object.assign(new Error('not found'),{code:'ENOTFOUND'});
  const reputation=await app.reputationCheck('example.com',{resolver:{resolveMx:async()=>[{priority:10,exchange:'mail.example.com'}],resolve4:async name=>{if(name==='mail.example.com')return ['192.0.2.25'];throw missingDns;},resolve6:async()=>{throw missingDns;}}});
  assert.strictEqual(reputation.status,'healthy');
  assert.strictEqual(reputation.evidence.checks.length,3);
  const enforcedDmarc={evidence:{tags:{p:'reject',pct:'100'}}};
  const ignoredNoLogo=await app.bimi('example.com',enforcedDmarc,{no_logo:{mode:'permanent'}},{txt:async()=>[]});
  assert.strictEqual(ignoredNoLogo.status,'ignored');
  assert.strictEqual(ignoredNoLogo.evidence.ignore_reason,'no_logo');
  const visibleNoLogo=await app.bimi('example.com',enforcedDmarc,null,{txt:async()=>[]});
  assert.strictEqual(visibleNoLogo.status,'warning');
  assert.strictEqual(app.smtpTimingTest('SMTP Connection Time',7300,5000,15000).status,'warning');
  const smtpEndpoint=app.evaluateSmtpEvidence('mail.example.com',{host:'mail.example.com',port:25,ip_address:'192.0.2.25',connection_time_ms:7300,transaction_time_ms:7966,reverse_dns:['mail.example.com'],forward_confirmed:true,reverse_dns_match:true,banner_hostname:'mail.example.com',banner_matches_reverse_dns:true,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,tls_protocol:'TLSv1.3',relay_status:'denied',rcpt_to_code:550,transcript:[]});
  assert.strictEqual(smtpEndpoint.status,'info');
  assert.strictEqual(smtpEndpoint.tests.find(test=>test.label==='SMTP Connection Time').status,'info');
  assert.strictEqual(smtpEndpoint.tests.find(test=>test.label==='SMTP Reverse DNS').status,'healthy');
  assert.strictEqual(smtpEndpoint.tests.find(test=>test.label==='SMTP Open Relay').status,'healthy');
  const relayEndpoint=app.evaluateSmtpEvidence('mail.example.com',{connection_time_ms:200,transaction_time_ms:400,reverse_dns:['mail.example.com'],forward_confirmed:true,reverse_dns_match:true,banner_hostname:'mail.example.com',banner_matches_reverse_dns:true,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'potential',rcpt_to_code:250,transcript:[]});
  assert.strictEqual(relayEndpoint.status,'warning');
  assert.match(relayEndpoint.tests.find(test=>test.label==='SMTP Open Relay').value,/External verification required/);
  const externalRelay=app.evaluateSmtpEvidence('mail.example.com',{connection_time_ms:200,transaction_time_ms:400,reverse_dns:['mail.example.com'],forward_confirmed:true,banner_hostname:'mail.example.com',starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'potential',rcpt_to_code:250,transcript:[]},{...app.smtpProfile('example.com',{hosting_type:'self_hosted',relay_context:'external'},[{exchange:'mail.example.com'}])});
  assert.strictEqual(externalRelay.tests.find(test=>test.label==='SMTP Open Relay').status,'critical');
  const smtpCheck=app.smtpResult('example.com',[{priority:10,exchange:'mail.example.com'}],[smtpEndpoint]);
  assert.strictEqual(smtpCheck.id,'smtp_service');
  assert.strictEqual(smtpCheck.status,'info');
  const managedEndpoint=app.evaluateSmtpEvidence('mx.hover.com.cust.hostedemail.com',{connection_time_ms:200,transaction_time_ms:400,ip_address:'192.0.2.30',reverse_dns:['mail30.hostedemail.com'],forward_confirmed:true,banner:'220 mail30.hostedemail.com ESMTP ready',banner_hostname:'mail30.hostedemail.com',starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'denied',rcpt_to_code:550,transcript:[]},hoverProfile);
  assert.strictEqual(managedEndpoint.status,'healthy');
  assert.strictEqual(managedEndpoint.tests.find(test=>test.label==='SMTP Reverse DNS').status,'healthy');
  assert.strictEqual(managedEndpoint.tests.find(test=>test.label==='SMTP Banner Check').status,'healthy');
  const nonstandardIcloudIdentity=app.evaluateSmtpEvidence('mx01.mail.icloud.com',{connection_time_ms:200,transaction_time_ms:400,ip_address:'192.0.2.31',reverse_dns:['nonstandard-name'],forward_confirmed:true,banner:'220 nonstandard greeting',banner_hostname:null,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'denied',rcpt_to_code:550,transcript:[]},icloudProfile);
  assert.strictEqual(nonstandardIcloudIdentity.status,'info');
  assert.strictEqual(nonstandardIcloudIdentity.tests.find(test=>test.label==='SMTP Valid Hostname').status,'info');
  assert.strictEqual(nonstandardIcloudIdentity.tests.find(test=>test.label==='SMTP Banner Check').status,'info');
  const enforcedSts=app.reconcileMtaSts({id:'mta_sts',label:'MTA-STS',status:'healthy',summary:'Enforced',detail:'One MX host is covered.',evidence:{policy:{mode:'enforce'}}},{evidence:{endpoints:[{host:'mx.example.com',starttls_negotiated:true,tls_authorized:false}]}});
  assert.strictEqual(enforcedSts.status,'critical');
  assert.deepStrictEqual(enforcedSts.evidence.smtp_validation_failed_hosts,['mx.example.com']);
  const blockedSts=app.reconcileMtaSts({id:'mta_sts',label:'MTA-STS',status:'healthy',summary:'Enforced',detail:'One MX host is covered.',evidence:{policy:{mode:'enforce'}}},{evidence:{endpoints:[{host:'mx.example.com',policy_blocked:true,starttls_negotiated:false}]}});
  assert.strictEqual(blockedSts.status,'healthy');
  const injectedSmtp=await app.smtpDiagnostics('example.com',{timeout_ms:8000,resolver:{resolveMx:async()=>[{priority:10,exchange:'mail.example.com'}]},probe:async()=>({host:'mail.example.com',port:25,ip_address:'192.0.2.25',connection_time_ms:100,transaction_time_ms:300,reverse_dns:['mail.example.com'],forward_confirmed:true,reverse_dns_match:true,banner_hostname:'mail.example.com',banner_matches_reverse_dns:true,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'denied',rcpt_to_code:550,transcript:[]})});
  assert.strictEqual(injectedSmtp.status,'healthy');
  let coordinatorNow=Date.parse('2026-10-06T12:00:00Z'),coordinatorCalls=0,activeProbes=0,maxActiveProbes=0;
  const coordinator=smtpMonitor.createSmtpProbeCoordinator({concurrency:1,cooldown_ms:60000,jitter_ratio:0,now:()=>coordinatorNow,probe:async host=>{coordinatorCalls+=1;activeProbes+=1;maxActiveProbes=Math.max(maxActiveProbes,activeProbes);await new Promise(resolve=>setImmediate(resolve));activeProbes-=1;return {host,port:25,connection_time_ms:100,transaction_time_ms:200,reverse_dns:[host],transcript:[]};}});
  const sharedProbes=await Promise.all([coordinator.probe('shared.mx.example'),coordinator.probe('shared.mx.example')]);
  assert.strictEqual(coordinatorCalls,1,'simultaneous requests for a shared MX host must use one live probe');
  assert.strictEqual(sharedProbes.filter(probe=>probe.probe_shared).length,1);
  const cachedProbe=await coordinator.probe('shared.mx.example');
  assert.strictEqual(cachedProbe.probe_cached,true);
  assert.strictEqual(coordinatorCalls,1,'the per-MX cooldown must prevent another live probe');
  await Promise.all([coordinator.probe('first.mx.example'),coordinator.probe('second.mx.example')]);
  assert.strictEqual(maxActiveProbes,1,'the global SMTP probe concurrency limit must be enforced');
  let backoffNow=Date.parse('2026-10-06T12:00:00Z'),backoffCalls=0;
  const backoffCoordinator=smtpMonitor.createSmtpProbeCoordinator({concurrency:1,cooldown_ms:60000,backoff_ms:60000,max_backoff_ms:240000,jitter_ratio:0,now:()=>backoffNow,probe:async host=>{backoffCalls+=1;return {host,port:25,greeting_code:421,banner:'421 4.4.5 Too many SMTP connections from this host',rate_limited:true,reverse_dns:[],transcript:[]};}});
  const firstLimited=await backoffCoordinator.probe('limited.mx.example');
  assert.strictEqual(Date.parse(firstLimited.next_probe_at)-backoffNow,60000);
  assert.strictEqual((await backoffCoordinator.probe('limited.mx.example')).probe_cached,true);
  assert.strictEqual(backoffCalls,1);
  backoffNow+=60001;
  const secondLimited=await backoffCoordinator.probe('limited.mx.example');
  assert.strictEqual(Date.parse(secondLimited.next_probe_at)-backoffNow,120000,'repeated SMTP 421 responses must increase the backoff');
  const smtpServer=net.createServer(socket=>{socket.write('220 mail.example.com ESMTP ready\r\n');let input='';socket.on('data',chunk=>{input+=chunk.toString();while(input.includes('\n')){const end=input.indexOf('\n');const line=input.slice(0,end).trim();input=input.slice(end+1);if(/^EHLO /i.test(line))socket.write('250-mail.example.com\r\n250 PIPELINING\r\n');else if(/^MAIL FROM:/i.test(line))socket.write('250 Sender accepted\r\n');else if(/^RCPT TO:/i.test(line))socket.write('550 Relaying denied\r\n');else if(/^RSET/i.test(line))socket.write('250 Reset\r\n');else if(/^QUIT/i.test(line)){socket.write('221 Bye\r\n');socket.end();}}});});
  await new Promise((resolve,reject)=>{smtpServer.once('error',reject);smtpServer.listen(0,'127.0.0.1',resolve);});
  const localPort=smtpServer.address().port;
  const localProbe=await require('../smtp').probeSmtp('127.0.0.1',{port:localPort,timeout_ms:2000,resolver:{reverse:async()=>['mail.example.com'],lookup:async()=>[{address:'127.0.0.1'}]}});
  await new Promise(resolve=>smtpServer.close(resolve));
  assert.strictEqual(localProbe.greeting_code,220);
  assert.strictEqual(localProbe.relay_status,'denied');
  assert.strictEqual(localProbe.rcpt_to_code,550);
  assert.strictEqual(localProbe.ehlo_identity,'[127.0.0.1]');
  const rateLimitedServer=net.createServer(socket=>socket.end('421 4.4.5 Too many SMTP connections from this host\r\n'));
  await new Promise((resolve,reject)=>{rateLimitedServer.once('error',reject);rateLimitedServer.listen(0,'127.0.0.1',resolve);});
  const rateLimitedProbe=await smtpMonitor.probeSmtp('127.0.0.1',{port:rateLimitedServer.address().port,timeout_ms:2000,resolver:{reverse:async()=>[],lookup:async()=>[]}});
  await new Promise(resolve=>rateLimitedServer.close(resolve));
  assert.strictEqual(rateLimitedProbe.greeting_code,421);
  assert.strictEqual(rateLimitedProbe.rate_limited,true);
  const rateLimitedEndpoint=app.evaluateSmtpEvidence('limited.mx.example',{...rateLimitedProbe,next_probe_at:'2026-10-06T12:15:00.000Z'},hoverProfile);
  assert.strictEqual(rateLimitedEndpoint.status,'warning');
  assert.match(rateLimitedEndpoint.tests.find(test=>test.label==='SMTP Connection Time').value,/rate limited/i);
  assert.strictEqual(rateLimitedEndpoint.tests.find(test=>test.label==='SMTP TLS').status,'info');
  assert.strictEqual(rateLimitedEndpoint.tests.find(test=>test.label==='SMTP Open Relay').status,'info');
  const rateLimitedCheck=app.smtpResult('example.com',[{priority:10,exchange:'limited.mx.example'}],[rateLimitedEndpoint],hoverProfile);
  assert.match(rateLimitedCheck.action,/back off automatically/);
  let blockedMailFrom=false;
  const blockedServer=net.createServer(socket=>{socket.write('220 mx.hostedemail.com ESMTP ready\r\n');let input='';socket.on('data',chunk=>{input+=chunk.toString();while(input.includes('\n')){const end=input.indexOf('\n');const line=input.slice(0,end).trim();input=input.slice(end+1);if(/^EHLO /i.test(line))socket.write('250-mx.hostedemail.com\r\n250 STARTTLS\r\n');else if(/^STARTTLS/i.test(line))socket.write('503 5.7.0 Error: access denied for monitoring source\r\n');else if(/^MAIL FROM:/i.test(line)){blockedMailFrom=true;socket.write('503 5.7.0 Error: access denied\r\n');}else if(/^QUIT/i.test(line)){socket.write('221 Bye\r\n');socket.end();}}});});
  await new Promise((resolve,reject)=>{blockedServer.once('error',reject);blockedServer.listen(0,'127.0.0.1',resolve);});
  const blockedProbe=await require('../smtp').probeSmtp('127.0.0.1',{port:blockedServer.address().port,timeout_ms:2000,resolver:{reverse:async()=>['mx.hostedemail.com'],lookup:async()=>[{address:'192.0.2.20'}]}});
  await new Promise(resolve=>blockedServer.close(resolve));
  assert.strictEqual(blockedProbe.policy_blocked,true);
  assert.strictEqual(blockedProbe.policy_blocked_command,'STARTTLS');
  assert.strictEqual(blockedMailFrom,false);
  assert.ok(blockedProbe.transcript.findIndex(line=>line==='C: STARTTLS')>blockedProbe.transcript.findIndex(line=>line===`C: EHLO ${blockedProbe.ehlo_identity}`));
  const blockedEndpoint=app.evaluateSmtpEvidence('mx.hostedemail.com',{...blockedProbe,ip_address:'192.0.2.25',reverse_dns:['shared.hostedemail.com'],ptr_matches_host:false,forward_confirmed:true,banner_hostname:'mx.hostedemail.com',banner_matches_reverse_dns:false},hoverProfile);
  assert.strictEqual(blockedEndpoint.status,'info');
  assert.strictEqual(blockedEndpoint.tests.find(test=>test.label==='SMTP Reverse DNS').status,'healthy');
  assert.match(blockedEndpoint.tests.find(test=>test.label==='SMTP TLS').value,/Not tested/);
  assert.match(blockedEndpoint.tests.find(test=>test.label==='SMTP Open Relay').value,/Not tested/);
  const blockedCheck=app.smtpResult('example.com',[{priority:10,exchange:'mx.hostedemail.com'}],[blockedEndpoint],hoverProfile);
  assert.strictEqual(blockedCheck.status,'info');
  assert.match(blockedCheck.action,/permitted external probe address/);
  const nullMx=await app.smtpDiagnostics('example.com',{profile:{hosting_type:'no_inbound'},resolver:{resolveMx:async()=>[{priority:0,exchange:'.'}]}});
  assert.strictEqual(nullMx.status,'healthy');
  assert.strictEqual(nullMx.evidence.null_mx,true);
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}},'source_ip_address.keyword':{keyword:{aggregatable:true}}}),'source_ip_address.keyword');
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}}}),null);
  assert.strictEqual(app.matchesIndexPattern('dmarc_aggregate-2026.09','dmarc_aggregate*'),true);
  const shards=app.unassignedShardSummary([{index:'security-auditlog-2026.09.03',prirep:'r',state:'UNASSIGNED'},{index:'.opendistro-ism-config',prirep:'r',state:'UNASSIGNED'},{index:'dmarc_aggregate-2026.09',prirep:'p',state:'STARTED'}],settings);
  assert.strictEqual(shards.total,2);
  assert.strictEqual(shards.all_replicas,true);
  assert.strictEqual(shards.affected_report_shards,0);
  assert.strictEqual(shards.groups.find(group=>group.category==='OpenSearch security audit logs').unassigned_shards,1);
  process.env.DEMO_MODE='true';const status=await app.refresh();assert.strictEqual(status.domains.length,1);assert.ok(status.summary.critical>0);assert.strictEqual(status.version,require('../package.json').version);assert.strictEqual(status.domains[0].mail_profile.provider,'self_hosted');
  assert.strictEqual(require('../package.json').version,'3.4.0');
  const page=fs.readFileSync('public/index.html','utf8'),client=fs.readFileSync('public/app.js','utf8'),styles=fs.readFileSync('public/settings.css','utf8'),icon=fs.readFileSync('public/domainposture.svg','utf8'),standalone=fs.readFileSync('compose.standalone.yml','utf8'),dockerfile=fs.readFileSync('Dockerfile','utf8'),smtpSource=fs.readFileSync('smtp.js','utf8'),dnsToolsSource=fs.readFileSync('dns-tools.js','utf8'),networkToolsSource=fs.readFileSync('network-tools.js','utf8'),serverSource=fs.readFileSync('server.js','utf8');
  assert.match(page,/DomainPosture/);
  assert.match(page,/id="dashboard-view"/);
  assert.match(page,/id="settings-view"/);
  assert.match(page,/id="system-status-view"/);
  assert.match(page,/id="tools-view"/);
  assert.match(page,/id="lookup-form"/);
  assert.match(page,/id="lookup-tool"/);
  assert.match(page,/DNSSEC validation/);
  assert.match(page,/Domain registration \(RDAP\)/);
  assert.match(page,/ASN and IP ownership/);
  assert.match(page,/TCP port connectivity/);
  assert.match(page,/href="\/tools"/);
  assert.doesNotMatch(page,/id="system-status-tab"/);
  assert.match(page,/id="system-status-indicator"/);
  assert.match(page,/aria-label="Dashboard" title="Dashboard"/);
  assert.match(page,/aria-label="Domains" title="Domains"/);
  assert.match(page,/aria-label="Lookup Center" title="Lookup Center"/);
  assert.match(page,/id="system-log"/);
  assert.match(page,/id="log-service"/);
  assert.match(page,/id="service-log"/);
  assert.match(page,/id="service-log-service"/);
  assert.match(page,/v3\.4\.0/);
  assert.match(page,/Domain Health Dashboard/);
  assert.doesNotMatch(page,/DMARC authentication and SMTP TLS delivery results for the selected history window/);
  assert.match(page,/id="domain-menu-button"/);
  assert.match(page,/id="domain-menu-list"/);
  assert.match(page,/id="system-status-indicator"/);
  assert.match(page,/name="domain-sort" value="priority"/);
  assert.match(page,/name="domain-sort" value="alphabetical"/);
  assert.ok(page.indexOf('domain-attention-heading') < page.indexOf('id="attention"'));
  assert.match(page,/Event history/);
  assert.match(page,/id="bimi-ignore-mode"/);
  assert.match(page,/id="bimi-ignore-months"/);
  assert.match(page,/id="bimi-no-logo-ignore-mode"/);
  assert.match(page,/id="bimi-no-logo-ignore-months"/);
  assert.match(page,/id="mta-sts-ignore-mode"/);
  assert.match(page,/id="mta-sts-ignore-months"/);
  assert.doesNotMatch(page,/id="tls-certificates-ignore-mode"/);
  assert.match(page,/id="smtp-probe-hostname"/);
  assert.match(page,/id="smtp-probe-cooldown"/);
  assert.match(page,/id="dns-change-confirmations"/);
  assert.match(page,/id="dns-notifications-enabled"/);
  assert.match(page,/id="dns-monitoring-enabled"/);
  assert.match(page,/id="dns-monitor-list"/);
  assert.match(fs.readFileSync(path.join(__dirname,'..','Dockerfile'),'utf8'),/\bdns-tools\.js\b/);
  assert.match(page,/id="smtp-hosting-type"/);
  assert.match(page,/id="smtp-provider"/);
  assert.match(page,/Kerio Connect/);
  assert.match(page,/Hover Mail/);
  assert.match(page,/id="smtp-relay-context"/);
  assert.match(page,/id="check-public-certificate"/);
  assert.match(page,/id="check-origin-certificate"/);
  assert.match(page,/id="origin-ip"/);
  for(const id of ['section-domain-certificates','section-additional-tls','section-smtp','section-dkim','section-mail-security','section-bimi']) assert.match(page,new RegExp(`id="${id}"`));
  const domainEditor=page.slice(page.indexOf('<dialog id="domain-dialog"'),page.indexOf('</dialog>',page.indexOf('<dialog id="domain-dialog"')));
  for(const [before,after] of [['Domain certificates','Additional TLS endpoints'],['Additional TLS endpoints','Mail hosting and SMTP probes'],['Mail hosting and SMTP probes','DKIM selectors'],['DKIM selectors','Mail security review exceptions'],['Mail security review exceptions','BIMI review exceptions']]) assert.ok(domainEditor.indexOf(before)<domainEditor.indexOf(after),`${before} must appear before ${after}`);
  assert.match(page,/id="certificate-check-minutes"/);
  assert.match(page,/id="discord-webhook"/);
  assert.doesNotMatch(page,/id="discord-webhook-clear"/);
  assert.match(page,/id="change-discord-webhook"/);
  assert.match(page,/id="test-discord-webhook"/);
  assert.match(page,/id="rotate-secrets-key"/);
  assert.match(page,/id="discord-enabled"/);
  assert.match(page,/id="ssl-warning-threshold"/);
  assert.match(page,/IP and domain reputation/);
  assert.match(page,/Observed email traffic/);
  assert.ok(page.indexOf('id="attention"') < page.indexOf('class="matrix"'));
  assert.ok(page.indexOf('class="matrix"') < page.indexOf('id="report-center"'));
  assert.match(page,/SMTP service/);
  assert.match(page,/they never send DATA or message content/);
  assert.match(page,/href="\/status"/);
  assert.match(page,/dashboard-icon/);
  assert.match(page,/monitored-domains-icon/);
  assert.match(page,/id="system-status-indicator"[^>]*href="\/status"/);
  assert.match(page,/run-checks-icon/);
  assert.match(page,/settings-icon/);
  assert.match(page,/id="organization-reports"/);
  assert.match(page,/id="domain-reports"/);
  assert.match(page,/id="report-source"/);
  assert.match(page,/id="mailbox-enabled"/);
  assert.match(page,/id="snapshots-enabled"/);
  assert.match(page,/role="tablist"/);
  assert.match(page,/data-settings-tab="parsedmarc"/);
  assert.match(page,/data-settings-tab="general"/);
  for(const [before,after] of [['data-settings-tab="domains"','data-settings-tab="appearance"'],['data-settings-tab="appearance"','data-settings-tab="opensearch"'],['data-settings-tab="opensearch"','data-settings-tab="parsedmarc"'],['data-settings-tab="parsedmarc"','data-settings-tab="general"']]) assert.ok(page.indexOf(before)<page.indexOf(after),`${before} must appear before ${after}`);
  assert.match(page,/domains-icon/);
  assert.match(page,/appearance-icon/);
  assert.match(page,/opensearch-icon/);
  assert.match(page,/parsedmarc-icon/);
  assert.match(page,/id="pm-delete-smtp-tls"/);
  assert.match(page,/Archive\/SMTP-TLS/);
  assert.match(page,/id="help-view"/);
  assert.match(page,/id="domain-dialog"/);
  assert.match(page,/name="theme" value="system"/);
  assert.match(page,/aria-label="Settings"/);
  assert.match(page,/id="version"/);
  assert.match(client,/card-context/);
  assert.match(client,/renderDashboard/);
  assert.match(client,/renderSettingsDomains/);
  assert.match(client,/organizationReports/);
  assert.match(client,/reportingOrganizationsCard/);
  assert.match(client,/Individual DMARC failure reports \(RUF\)/);
  assert.match(client,/api\/system-logs/);
  assert.match(client,/api\/service-logs/);
  assert.match(client,/sourceList/);
  assert.match(client,/Reporter name not provided/);
  assert.match(client,/Scope:/);
  assert.match(client,/api\/bimi-logo/);
  assert.match(client,/bimi_exceptions/);
  assert.match(client,/bimiExceptionDirty/);
  assert.match(client,/control_exceptions/);
  assert.match(client,/controlExceptionDirty/);
  assert.match(client,/dmarcReportersCard/);
  assert.match(client,/passed_dkim_aligned_rate/);
  assert.match(client,/hasFailures/);
  const detailLayout=client.slice(client.indexOf('function detailCards'),client.indexOf('function organizationReports'));
  for(const [before,after] of [['report-dmarc','report-smtp-tls'],['report-smtp-tls','report-dmarc-sources'],['report-dmarc-sources','report-smtp-tls-organizations'],['report-smtp-tls-organizations','report-dmarc-failure'],['report-dmarc-failure','report-smtp-tls-failures'],['report-smtp-tls-failures','report-dmarc-reporters']]) assert.ok(detailLayout.indexOf(before)<detailLayout.indexOf(after),`${before} must appear before ${after}`);
  assert.match(client,/ignored: 'Ignored'/);
  assert.match(client,/smtpDiagnosticsCard/);
  assert.match(client,/report-smtp-diagnostics/);
  assert.match(client,/detailCards\(domain\.reports, domain\.check_sections, domain\.dns_monitoring_enabled\)/);
  assert.match(client,/Checks switched off/);
  assert.match(client,/certificate-days/);
  assert.match(client,/certificateControlCard/);
  assert.match(client,/data-check-now/);
  assert.match(client,/issue-status/);
  assert.match(client,/data-report-target/);
  assert.match(client,/selectSettingsTab/);
  assert.match(client,/renderDomainMenu/);
  assert.match(client,/domainposture-domain-sort/);
  assert.match(client,/updateDomainSectionVisibility/);
  assert.match(client,/input\[type="checkbox"\].*role.*switch/);
  assert.match(client,/MX endpoint results/);
  assert.match(client,/Monitoring checks are refreshing in the background/);
  assert.match(client,/probe_cached/);
  assert.match(client,/api\/tools\/lookup/);
  assert.match(client,/lookupToolHelp/);
  assert.match(client,/tcp_port/);
  assert.match(client,/dnsMonitoringCard/);
  assert.match(client,/DNS record monitor/);
  assert.match(client,/function scoreStatus/);
  assert.match(client,/scoreValue >= 90/);
  assert.match(client,/scoreValue >= 70/);
  assert.match(client,/Public.*Cert Expiration/);
  assert.match(client,/Origin.*Cert Expiration/);
  assert.match(client,/domain\.ssl_warning_threshold/);
  assert.match(client,/id="updated" class="master-updated"/);
  assert.match(smtpSource,/createSmtpProbeCoordinator/);
  assert.match(smtpSource,/rate_limited/);
  assert.match(dnsToolsSource,/resolveSoa/);
  assert.match(dnsToolsSource,/createLookupCenter/);
  assert.match(dnsToolsSource,/normalizeLookupTool/);
  assert.match(networkToolsSource,/DNSSEC_ENDPOINT/);
  assert.match(networkToolsSource,/RDAP_BOOTSTRAP_URL/);
  assert.match(networkToolsSource,/ALLOWED_TCP_PORTS/);
  assert.match(dockerfile,/network-tools\.js/);
  assert.match(serverSource,/processDnsChangeNotifications/);
  assert.match(serverSource,/lookupCenter\.lookup\(body\.target, body\.tool, body\.tcp_port\)/);
  assert.match(serverSource,/ssl_warning_threshold: config\.notifications\.ssl_warning_threshold/);
  const saveSettingsSource=serverSource.slice(serverSource.indexOf('async function saveSettings'),serverSource.indexOf('function settingsConfig'));
  assert.doesNotMatch(saveSettingsSource,/await configureSnapshots/,'saving settings must not wait for the OpenSearch snapshot API');
  assert.match(serverSource,/scheduleRefreshAfterSettingsSave\(settings\)/);
  assert.match(client,/issue\$\{domain\.counts\.critical === 1 \? ' needs' : 's need'\}/);
  assert.ok(fs.existsSync('compose.standalone.yml'));
  assert.match(standalone,/ghcr\.io\/domainaware\/parsedmarc/);
  assert.match(standalone,/DOMAINPOSTURE_SETTINGS_PATH/);
  assert.match(standalone,/MAILPOSTURE_SETTINGS_PATH/);
  assert.match(standalone,/DOMAINPOSTURE_DISCORD_WEBHOOK/);
  assert.doesNotMatch(standalone,/domainposture_secrets_key/);
  assert.match(standalone,/OPENSEARCH_DATA_PATH/);
  assert.match(standalone,/OPENSEARCH_SNAPSHOT_PATH/);
  assert.match(standalone,/type: bind/);
  assert.match(standalone,/target: \/etc\/parsedmarc\n\s+read_only: true/);
  assert.doesNotMatch(standalone,/target: \/etc\/parsedmarc:ro/);
  assert.match(standalone,/reloading parsedmarc/);
  assert.match(standalone,/parsedmarc_status/);
  assert.match(standalone,/write_status running/);
  assert.match(standalone,/SERVICE_LOGS_ENABLED: "true"/);
  assert.match(standalone,/opensearch_logs/);
  assert.match(standalone,/target: \/logs\/opensearch/);
  assert.match(standalone,/log_file="\/run\/mailposture\/parsedmarc\.log"/);
  assert.match(standalone,/wait_for_status=yellow/);
  assert.match(standalone,/timed_out/);
  assert.match(dockerfile,/smtp\.js/);
  assert.match(dockerfile,/dns-security\.js/);
  assert.match(dockerfile,/ssl-monitor\.js/);
  assert.match(dockerfile,/ghcr\.io\/idesyatov\/ssl-watch:v\$\{SSL_WATCH_VERSION\}/);
  assert.match(dockerfile,/org\.opencontainers\.image\.version="3\.4\.0"/);
  assert.match(smtpSource,/RCPT TO:<probe@example\.net>/);
  assert.doesNotMatch(smtpSource,/command\(['"]DATA/);
  assert.match(smtpSource,/policyBlock/);
  assert.ok(smtpSource.indexOf("reader.command('STARTTLS')") < smtpSource.indexOf("reader.command('MAIL FROM:<probe@example.com>')"));
  assert.match(styles,/#0c71c3/i);
  assert.match(styles,/monitored-domains\.svg/);
  assert.match(styles,/appearance\.svg/);
  assert.match(styles,/opensearch\.svg/);
  assert.match(styles,/parsedmarc\.svg/);
  assert.match(styles,/dashboard\.svg/);
  assert.match(styles,/run-checks\.svg/);
  assert.match(styles,/settings\.svg/);
  assert.match(styles,/status\.svg/);
  assert.match(styles,/system-status\.svg/);
  assert.match(styles,/\.domain-menu-list/);
  assert.match(styles,/\.score-watermark/);
  assert.match(styles,/@media\(max-width:980px\).*\.topnav \.toolbar-label/);
  assert.match(styles,/\.master-updated/);
  assert.match(styles,/#system-status-indicator/);
  assert.match(styles,/flex-direction:column-reverse/);
  assert.match(styles,/#system-status-indicator \.status-symbol/);
  assert.match(styles,/\.system-log/);
  assert.match(styles,/\.service-log/);
  assert.match(styles,/\.index-patterns/);
  assert.match(styles,/\.state\.ignored/);
  assert.match(styles,/Standard on\/off switch/);
  assert.match(styles,/translateX\(20px\)/);
  assert.match(page,/id="create-secrets-key"/);
  assert.match(page,/This key will not be shown again/);
  assert.match(client,/\/api\/secrets-key/);
  assert.match(client,/\/api\/secrets-key\/rotate/);
  assert.match(client,/\/api\/notifications\/discord\/test/);
  assert.match(client,/navigator\.clipboard\.writeText/);
  assert.match(styles,/--review:#ffd60a/i);
  assert.match(styles,/\.number-with-unit/);
  assert.match(styles,/\.general-icon/);
  assert.match(icon,/<svg/);
  assert.match(icon,/check mark/i);
  assert.match(icon,/#0C71C3/);
  for(const iconFile of ['appearance.svg','dashboard.svg','monitored-domains.svg','opensearch.svg','parsedmarc.svg','run-checks.svg','settings.svg','status.svg','system-status.svg']) assert.ok(fs.existsSync(`public/${iconFile}`));
  console.log('All DomainPosture checks passed.');
}
run().catch(e=>{console.error(e);process.exitCode=1});
