'use strict';
const assert=require('assert'),fs=require('fs'),net=require('net');
const app=require('../server');
async function run(){
  assert.deepStrictEqual(app.assignments('example.com=s1|s2;example.net=google'),{'example.com':['s1','s2'],'example.net':['google']});
  process.env.MONITORED_DOMAINS='example.com,example.net';
  process.env.DKIM_SELECTORS='example.com=s1|s2;example.net=google';
  process.env.TLS_ENDPOINTS='example.com=mta-sts.example.com:443|mail.example.com:465';
  process.env.OPENSEARCH_PASSWORD='test-only';
  const config=app.envConfig();
  assert.strictEqual(config.domains.length,2);
  assert.deepStrictEqual(config.domains[0].dkim_selectors,['s1','s2']);
  assert.deepStrictEqual(config.domains[0].tls_endpoints,[{host:'mta-sts.example.com',port:443},{host:'mail.example.com',port:465}]);
  const settings=app.normalizeSettings({monitored_domains:['Example.com'],dkim_selectors:{'example.com':['s1','s2']},tls_endpoints:{'example.com':[{host:'mail.example.com',port:465}]},smtp_profiles:{'example.com':{hosting_type:'self_hosted',provider:'auto',expected_hostname:'mail.example.com',relay_context:'external'}},smtp_probe_hostname:'probe.example.com',report_days:14,refresh_minutes:30,request_timeout_ms:5000,report_source:'standalone',opensearch_url:'http://parsedmarc-opensearch:9200',mailbox:{enabled:true,host:'imap.example.com',port:993,username:'reports@example.com',reports_folder:'INBOX',archive_folder:'Archive'},snapshots:{enabled:true,cron:'0 2 * * *',delete_cron:'30 2 * * *',timezone:'UTC',retention_days:30,min_count:7,max_count:60}});
  assert.deepStrictEqual(settings.monitored_domains,['example.com']);
  assert.strictEqual(settings.opensearch_enabled,true);
  assert.strictEqual(settings.report_source,'standalone');
  assert.strictEqual(settings.schema_version,6);
  assert.strictEqual(settings.smtp_probe_hostname,'probe.example.com');
  assert.deepStrictEqual(settings.smtp_profiles['example.com'],{hosting_type:'self_hosted',provider:'auto',expected_hostname:'mail.example.com',relay_context:'external'});
  assert.strictEqual(settings.mailbox.archive_folder,'Archive');
  assert.strictEqual(settings.parsedmarc.general.save_smtp_tls,true);
  assert.strictEqual(settings.parsedmarc.mailbox.delete_smtp_tls,false);
  assert.strictEqual(settings.parsedmarc.opensearch.number_of_replicas,0);
  assert.strictEqual(settings.parsedmarc.opensearch.monthly_indexes,true);
  assert.strictEqual(app.normalizeSettings({parsedmarc:{mailbox:{batch_size:0}}}).parsedmarc.mailbox.batch_size,0);
  assert.strictEqual(settings.snapshots.cron,'0 2 * * *');
  const bimiSettings=app.normalizeSettings({monitored_domains:['example.com'],bimi_exceptions:{'example.com':{mode:'permanent'},'other.example':{mode:'permanent'}}});
  assert.deepStrictEqual(bimiSettings.bimi_exceptions,{'example.com':{self_asserted:{mode:'permanent'}}});
  assert.deepStrictEqual(app.settingsConfig(bimiSettings).domains[0].bimi_exception,{self_asserted:{mode:'permanent'}});
  const noLogoSettings=app.normalizeSettings({monitored_domains:['example.com'],bimi_exceptions:{'example.com':{no_logo:{mode:'permanent'}}}});
  assert.deepStrictEqual(noLogoSettings.bimi_exceptions,{'example.com':{no_logo:{mode:'permanent'}}});
  assert.strictEqual(app.activeBimiException({mode:'permanent'}).active,true);
  assert.strictEqual(app.activeBimiException({mode:'until',expires_at:'2099-01-01T00:00:00.000Z'},Date.parse('2026-01-01T00:00:00.000Z')).active,true);
  assert.strictEqual(app.activeBimiException({mode:'until',expires_at:'2025-01-01T00:00:00.000Z'},Date.parse('2026-01-01T00:00:00.000Z')).active,false);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],bimi_exceptions:{'example.com':{mode:'until',expires_at:'not-a-date'}}}),/Invalid BIMI .*exception expiration/);
  const ignoredSummary=app.summarize('example.com',[{status:'healthy'},{status:'ignored'}]);
  assert.strictEqual(ignoredSummary.status,'healthy');
  assert.strictEqual(ignoredSummary.counts.ignored,1);
  process.env.OPENSEARCH_VERIFY_TLS='true';
  assert.strictEqual(app.normalizeSettings({monitored_domains:['example.com']}).opensearch_verify_tls,true);
  delete process.env.OPENSEARCH_VERIFY_TLS;
  assert.strictEqual(app.settingsConfig(settings).domains[0].report_days,14);
  assert.strictEqual(app.settingsConfig(settings).domains[0].smtp_profile.hosting_type,'self_hosted');
  assert.strictEqual(app.normalizeSettings({monitored_domains:['example.com'],smtp_profiles:{'example.com':{hosting_type:'self_hosted',provider:'kerio'}}}).smtp_profiles['example.com'].provider,'kerio');
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],smtp_probe_hostname:'not-a-host'}),/fully qualified/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['example.com'],smtp_profiles:{'example.com':{expected_hostname:'bad host'}}}),/expected SMTP hostname/);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['not a domain']}),/Invalid monitored domain/);
  assert.throws(()=>app.normalizeSettings({snapshots:{cron:'not cron'}}),/five-field cron/);
  assert.strictEqual(app.validCron('0 2 * * *'),true);
  assert.strictEqual(app.validCron('0 2 * *'),false);
  assert.strictEqual(app.validCron('99 2 * * *'),false);
  process.env.OPENSEARCH_PASSWORD='open%search';
  const ini=app.parsedmarcIni(settings,{imap_password:'test%secret'});
  assert.match(ini,/reports_folder = INBOX/);
  assert.match(ini,/archive_folder = Archive/);
  assert.match(ini,/password = test%%secret/);
  assert.match(ini,/password = open%%search/);
  assert.match(ini,/save_smtp_tls = True/);
  assert.match(ini,/delete_smtp_tls = False/);
  assert.match(ini,/since = 1d/);
  assert.match(ini,/number_of_replicas = 0/);
  assert.strictEqual(app.parsedmarcConfigurationStatus(settings,ini).status,'healthy');
  assert.strictEqual(app.parsedmarcConfigurationStatus({...settings,mailbox:{...settings.mailbox,enabled:false}},'').status,'warning');
  assert.strictEqual(app.parsedmarcConfigurationStatus(settings,'[general]\n[imap]\n').status,'critical');
  assert.strictEqual(app.overallStatus([{status:'healthy'},{status:'warning'}]),'warning');
  assert.strictEqual(app.overallStatus([{status:'warning'},{status:'critical'}]),'critical');
  assert.ok(Array.isArray(app.diagnosticLog().events));
  assert.strictEqual(app.redactLogText('password="private-value" token=abc123'),'password="[REDACTED]" token=[REDACTED]');
  assert.throws(()=>app.normalizeSettings({parsedmarc:{mailbox:{since:'yesterday'}}}),/number followed by/);
  const smtp=app.summarizeSmtpHits([{_source:{organization_name:'Sender',date_begin:'2026-09-01T00:00:00Z',policies:[{policy_domain:'example.com',successful_session_count:20,failed_session_count:2,failure_details:[{result_type:'validation-failure',failed_session_count:2}]}]}}],'example.com',7);
  assert.strictEqual(smtp.successful,20);
  assert.strictEqual(smtp.failed,2);
  assert.strictEqual(smtp.failure_types[0].type,'validation-failure');
  assert.strictEqual(smtp.raw_samples[0].organization_name,'Sender');
  assert.strictEqual(app.smtpOrganization({report_metadata:{organization_name:'Legacy Sender'}}),'Legacy Sender');
  assert.strictEqual(app.smtpOrganization({}, {organization_name:['Field Sender']}),'Field Sender');
  assert.strictEqual(app.smtpOrganization({}, {}),'Reporter name not provided');
  const dmarcReporters=app.summarizeDmarcReporters([{_source:{org_name:'Receiver',org_email:'reports@receiver.example',report_id:'one',date_end:'2026-09-02T00:00:00Z',message_count:4}},{_source:{org_name:'Receiver',org_email:'reports@receiver.example',report_id:'one',date_end:'2026-09-02T00:00:00Z',message_count:6}},{_source:{org_name:'Receiver',org_email:'reports@receiver.example',report_id:'two',date_end:'2026-09-03T00:00:00Z',message_count:2}}]);
  assert.strictEqual(dmarcReporters[0].domain,'receiver.example');
  assert.strictEqual(dmarcReporters[0].reports,2);
  assert.strictEqual(dmarcReporters[0].messages,12);
  const scopedSmtp=app.summarizeSmtpHits([{_index:'smtp_tls-1',_source:{organization_name:'Other',policies:[{policy_domain:'other.example',successful_session_count:1}]}},{_index:'smtp_tls-1',_source:{organization_name:'Ours',policies:[{policy_domain:'example.com',successful_session_count:2}]}}],'example.com',7);
  assert.strictEqual(scopedSmtp.raw_samples.length,1);
  assert.strictEqual(scopedSmtp.raw_samples[0].organization_name,'Ours');
  const attributedSmtp=app.summarizeSmtpHits([{_source:{organization_name:'Sender',contact_info:'mailto:tls-reports@sender.example',policies:[{policy_domain:'example.com',successful_session_count:3}]}}],'example.com',7);
  assert.deepStrictEqual(attributedSmtp.organizations[0].domains,['sender.example']);
  assert.strictEqual(app.mxMatch('mx1.example.com','*.example.com'),true);
  assert.strictEqual(app.smtpBannerHostname(['220 mail.example.com ESMTP ready']),'mail.example.com');
  assert.deepStrictEqual(app.smtpCapabilities(['250-mail.example.com','250-PIPELINING','250 STARTTLS']),['MAIL.EXAMPLE.COM','PIPELINING','STARTTLS']);
  assert.strictEqual(app.validSmtpHostname('mail.example.com'),true);
  assert.strictEqual(app.validSmtpHostname('localhost'),false);
  const hoverProfile=app.smtpProfile('seal.fyi',{hosting_type:'auto',provider:'auto'},[{exchange:'mx.hover.com.cust.hostedemail.com'}]);
  assert.strictEqual(hoverProfile.hosting_type,'managed');
  assert.strictEqual(hoverProfile.provider,'hover');
  assert.strictEqual(hoverProfile.provider_label,'Hover Mail');
  assert.strictEqual(hoverProfile.hosting_source,'auto_detected');
  assert.strictEqual(hoverProfile.provider_source,'auto_detected');
  const icloudProfile=app.smtpProfile('macsupportla.com',{hosting_type:'auto',provider:'auto'},[{exchange:'mx01.mail.icloud.com'},{exchange:'mx02.mail.icloud.com'}]);
  assert.strictEqual(icloudProfile.hosting_type,'managed');
  assert.strictEqual(icloudProfile.provider,'icloud');
  assert.strictEqual(icloudProfile.provider_label,'iCloud Mail');
  const kerioProfile=app.smtpProfile('sealsystems.net',{hosting_type:'auto',provider:'kerio'},[{exchange:'mail.sealsystems.net'}]);
  assert.strictEqual(kerioProfile.hosting_type,'self_hosted');
  assert.strictEqual(kerioProfile.provider,'kerio');
  assert.strictEqual(kerioProfile.provider_label,'Kerio Connect');
  assert.strictEqual(kerioProfile.hosting_source,'selected');
  assert.strictEqual(kerioProfile.provider_source,'selected');
  const spfResolver={resolveTxt:async name=>name==='example.com'?[['v=spf1 include:_spf.example.net -all']]:[['v=spf1 ip4:192.0.2.0/24 -all']]};
  const spf=await app.spfCheck('example.com',{resolver:spfResolver});
  assert.strictEqual(spf.status,'healthy');
  assert.strictEqual(spf.evidence.dns_lookup_terms,1);
  const softSpf=await app.spfCheck('example.com',{resolver:{resolveTxt:async()=>[['v=spf1 ~all']]}});
  assert.strictEqual(softSpf.status,'warning');
  const hoverSoftSpf=await app.spfCheck('example.com',{mail_profile:hoverProfile,resolver:{resolveTxt:async()=>[['v=spf1 ~all']]}});
  assert.strictEqual(hoverSoftSpf.status,'info');
  assert.match(hoverSoftSpf.action,/Hover-provided/);
  const unsafeSpf=await app.spfCheck('example.com',{resolver:{resolveTxt:async()=>[['v=spf1 +all']]}});
  assert.strictEqual(unsafeSpf.status,'critical');
  const invalidSpf=await app.spfCheck('example.com',{resolver:{resolveTxt:async()=>[['v=spf1 ip4:192.0.2.1/33 -all']]}});
  assert.strictEqual(invalidSpf.status,'critical');
  const timeoutStarted=Date.now();
  const timedOutSpf=await app.spfCheck('example.com',{timeout_ms:20,resolver:{resolveTxt:()=>new Promise(()=>{})}});
  assert.strictEqual(timedOutSpf.status,'warning');
  assert.strictEqual(timedOutSpf.summary,'DNS check unavailable');
  assert.ok(Date.now()-timeoutStarted<500,'SPF validation must respect its timeout');
  const tlsRpt=app.validateTlsRptRecord('v=TLSRPTv1; rua=mailto:tls@example.com,https://reports.example.net/v1/tlsrpt');
  assert.strictEqual(tlsRpt.valid,true);
  assert.strictEqual(tlsRpt.destinations.length,2);
  assert.strictEqual(app.validateTlsRptRecord('v=TLSRPTv1; rua=ftp://example.com/report').valid,false);
  assert.strictEqual(app.reverseIp('192.0.2.25'),'25.2.0.192');
  const missingDns=Object.assign(new Error('not found'),{code:'ENOTFOUND'});
  const reputation=await app.reputationCheck('example.com',{resolver:{resolveMx:async()=>[{priority:10,exchange:'mail.example.com'}],resolve4:async name=>{if(name==='mail.example.com')return ['192.0.2.25'];throw missingDns;},resolve6:async()=>{throw missingDns;}}});
  assert.strictEqual(reputation.status,'healthy');
  assert.strictEqual(reputation.evidence.checks.length,3);
  const enforcedDmarc={evidence:{tags:{p:'reject',pct:'100'}}};
  const ignoredNoLogo=await app.bimi('example.com',enforcedDmarc,{no_logo:{mode:'permanent'}},{txt:async()=>[]});
  assert.strictEqual(ignoredNoLogo.status,'ignored');
  assert.strictEqual(ignoredNoLogo.evidence.ignore_reason,'no_logo');
  const visibleNoLogo=await app.bimi('example.com',enforcedDmarc,null,{txt:async()=>[]});
  assert.strictEqual(visibleNoLogo.status,'warning');
  assert.strictEqual(app.smtpTimingTest('SMTP Connection Time',7300,5000,15000).status,'warning');
  const smtpEndpoint=app.evaluateSmtpEvidence('mail.example.com',{host:'mail.example.com',port:25,ip_address:'192.0.2.25',connection_time_ms:7300,transaction_time_ms:7966,reverse_dns:['mail.example.com'],forward_confirmed:true,reverse_dns_match:true,banner_hostname:'mail.example.com',banner_matches_reverse_dns:true,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,tls_protocol:'TLSv1.3',relay_status:'denied',rcpt_to_code:550,transcript:[]});
  assert.strictEqual(smtpEndpoint.status,'info');
  assert.strictEqual(smtpEndpoint.tests.find(test=>test.label==='SMTP Connection Time').status,'info');
  assert.strictEqual(smtpEndpoint.tests.find(test=>test.label==='SMTP Reverse DNS').status,'healthy');
  assert.strictEqual(smtpEndpoint.tests.find(test=>test.label==='SMTP Open Relay').status,'healthy');
  const relayEndpoint=app.evaluateSmtpEvidence('mail.example.com',{connection_time_ms:200,transaction_time_ms:400,reverse_dns:['mail.example.com'],forward_confirmed:true,reverse_dns_match:true,banner_hostname:'mail.example.com',banner_matches_reverse_dns:true,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'potential',rcpt_to_code:250,transcript:[]});
  assert.strictEqual(relayEndpoint.status,'warning');
  assert.match(relayEndpoint.tests.find(test=>test.label==='SMTP Open Relay').value,/External verification required/);
  const externalRelay=app.evaluateSmtpEvidence('mail.example.com',{connection_time_ms:200,transaction_time_ms:400,reverse_dns:['mail.example.com'],forward_confirmed:true,banner_hostname:'mail.example.com',starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'potential',rcpt_to_code:250,transcript:[]},{...app.smtpProfile('example.com',{hosting_type:'self_hosted',relay_context:'external'},[{exchange:'mail.example.com'}])});
  assert.strictEqual(externalRelay.tests.find(test=>test.label==='SMTP Open Relay').status,'critical');
  const smtpCheck=app.smtpResult('example.com',[{priority:10,exchange:'mail.example.com'}],[smtpEndpoint]);
  assert.strictEqual(smtpCheck.id,'smtp_service');
  assert.strictEqual(smtpCheck.status,'info');
  const managedEndpoint=app.evaluateSmtpEvidence('mx.hover.com.cust.hostedemail.com',{connection_time_ms:200,transaction_time_ms:400,ip_address:'192.0.2.30',reverse_dns:['mail30.hostedemail.com'],forward_confirmed:true,banner:'220 mail30.hostedemail.com ESMTP ready',banner_hostname:'mail30.hostedemail.com',starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'denied',rcpt_to_code:550,transcript:[]},hoverProfile);
  assert.strictEqual(managedEndpoint.status,'healthy');
  assert.strictEqual(managedEndpoint.tests.find(test=>test.label==='SMTP Reverse DNS').status,'healthy');
  assert.strictEqual(managedEndpoint.tests.find(test=>test.label==='SMTP Banner Check').status,'healthy');
  const nonstandardIcloudIdentity=app.evaluateSmtpEvidence('mx01.mail.icloud.com',{connection_time_ms:200,transaction_time_ms:400,ip_address:'192.0.2.31',reverse_dns:['nonstandard-name'],forward_confirmed:true,banner:'220 nonstandard greeting',banner_hostname:null,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'denied',rcpt_to_code:550,transcript:[]},icloudProfile);
  assert.strictEqual(nonstandardIcloudIdentity.status,'info');
  assert.strictEqual(nonstandardIcloudIdentity.tests.find(test=>test.label==='SMTP Valid Hostname').status,'info');
  assert.strictEqual(nonstandardIcloudIdentity.tests.find(test=>test.label==='SMTP Banner Check').status,'info');
  const enforcedSts=app.reconcileMtaSts({id:'mta_sts',label:'MTA-STS',status:'healthy',summary:'Enforced',detail:'One MX host is covered.',evidence:{policy:{mode:'enforce'}}},{evidence:{endpoints:[{host:'mx.example.com',starttls_negotiated:true,tls_authorized:false}]}});
  assert.strictEqual(enforcedSts.status,'critical');
  assert.deepStrictEqual(enforcedSts.evidence.smtp_validation_failed_hosts,['mx.example.com']);
  const blockedSts=app.reconcileMtaSts({id:'mta_sts',label:'MTA-STS',status:'healthy',summary:'Enforced',detail:'One MX host is covered.',evidence:{policy:{mode:'enforce'}}},{evidence:{endpoints:[{host:'mx.example.com',policy_blocked:true,starttls_negotiated:false}]}});
  assert.strictEqual(blockedSts.status,'healthy');
  const injectedSmtp=await app.smtpDiagnostics('example.com',{timeout_ms:8000,resolver:{resolveMx:async()=>[{priority:10,exchange:'mail.example.com'}]},probe:async()=>({host:'mail.example.com',port:25,ip_address:'192.0.2.25',connection_time_ms:100,transaction_time_ms:300,reverse_dns:['mail.example.com'],forward_confirmed:true,reverse_dns_match:true,banner_hostname:'mail.example.com',banner_matches_reverse_dns:true,starttls_advertised:true,starttls_negotiated:true,tls_authorized:true,relay_status:'denied',rcpt_to_code:550,transcript:[]})});
  assert.strictEqual(injectedSmtp.status,'healthy');
  const smtpServer=net.createServer(socket=>{socket.write('220 mail.example.com ESMTP ready\r\n');let input='';socket.on('data',chunk=>{input+=chunk.toString();while(input.includes('\n')){const end=input.indexOf('\n');const line=input.slice(0,end).trim();input=input.slice(end+1);if(/^EHLO /i.test(line))socket.write('250-mail.example.com\r\n250 PIPELINING\r\n');else if(/^MAIL FROM:/i.test(line))socket.write('250 Sender accepted\r\n');else if(/^RCPT TO:/i.test(line))socket.write('550 Relaying denied\r\n');else if(/^RSET/i.test(line))socket.write('250 Reset\r\n');else if(/^QUIT/i.test(line)){socket.write('221 Bye\r\n');socket.end();}}});});
  await new Promise((resolve,reject)=>{smtpServer.once('error',reject);smtpServer.listen(0,'127.0.0.1',resolve);});
  const localPort=smtpServer.address().port;
  const localProbe=await require('../smtp').probeSmtp('127.0.0.1',{port:localPort,timeout_ms:2000,resolver:{reverse:async()=>['mail.example.com'],lookup:async()=>[{address:'127.0.0.1'}]}});
  await new Promise(resolve=>smtpServer.close(resolve));
  assert.strictEqual(localProbe.greeting_code,220);
  assert.strictEqual(localProbe.relay_status,'denied');
  assert.strictEqual(localProbe.rcpt_to_code,550);
  assert.strictEqual(localProbe.ehlo_identity,'[127.0.0.1]');
  let blockedMailFrom=false;
  const blockedServer=net.createServer(socket=>{socket.write('220 mx.hostedemail.com ESMTP ready\r\n');let input='';socket.on('data',chunk=>{input+=chunk.toString();while(input.includes('\n')){const end=input.indexOf('\n');const line=input.slice(0,end).trim();input=input.slice(end+1);if(/^EHLO /i.test(line))socket.write('250-mx.hostedemail.com\r\n250 STARTTLS\r\n');else if(/^STARTTLS/i.test(line))socket.write('503 5.7.0 Error: access denied for monitoring source\r\n');else if(/^MAIL FROM:/i.test(line)){blockedMailFrom=true;socket.write('503 5.7.0 Error: access denied\r\n');}else if(/^QUIT/i.test(line)){socket.write('221 Bye\r\n');socket.end();}}});});
  await new Promise((resolve,reject)=>{blockedServer.once('error',reject);blockedServer.listen(0,'127.0.0.1',resolve);});
  const blockedProbe=await require('../smtp').probeSmtp('127.0.0.1',{port:blockedServer.address().port,timeout_ms:2000,resolver:{reverse:async()=>['mx.hostedemail.com'],lookup:async()=>[{address:'192.0.2.20'}]}});
  await new Promise(resolve=>blockedServer.close(resolve));
  assert.strictEqual(blockedProbe.policy_blocked,true);
  assert.strictEqual(blockedProbe.policy_blocked_command,'STARTTLS');
  assert.strictEqual(blockedMailFrom,false);
  assert.ok(blockedProbe.transcript.findIndex(line=>line==='C: STARTTLS')>blockedProbe.transcript.findIndex(line=>line===`C: EHLO ${blockedProbe.ehlo_identity}`));
  const blockedEndpoint=app.evaluateSmtpEvidence('mx.hostedemail.com',{...blockedProbe,ip_address:'192.0.2.25',reverse_dns:['shared.hostedemail.com'],ptr_matches_host:false,forward_confirmed:true,banner_hostname:'mx.hostedemail.com',banner_matches_reverse_dns:false},hoverProfile);
  assert.strictEqual(blockedEndpoint.status,'info');
  assert.strictEqual(blockedEndpoint.tests.find(test=>test.label==='SMTP Reverse DNS').status,'healthy');
  assert.match(blockedEndpoint.tests.find(test=>test.label==='SMTP TLS').value,/Not tested/);
  assert.match(blockedEndpoint.tests.find(test=>test.label==='SMTP Open Relay').value,/Not tested/);
  const blockedCheck=app.smtpResult('example.com',[{priority:10,exchange:'mx.hostedemail.com'}],[blockedEndpoint],hoverProfile);
  assert.strictEqual(blockedCheck.status,'info');
  assert.match(blockedCheck.action,/permitted external probe address/);
  const nullMx=await app.smtpDiagnostics('example.com',{profile:{hosting_type:'no_inbound'},resolver:{resolveMx:async()=>[{priority:0,exchange:'.'}]}});
  assert.strictEqual(nullMx.status,'healthy');
  assert.strictEqual(nullMx.evidence.null_mx,true);
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}},'source_ip_address.keyword':{keyword:{aggregatable:true}}}),'source_ip_address.keyword');
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}}}),null);
  assert.strictEqual(app.matchesIndexPattern('dmarc_aggregate-2026.09','dmarc_aggregate*'),true);
  const shards=app.unassignedShardSummary([{index:'security-auditlog-2026.09.03',prirep:'r',state:'UNASSIGNED'},{index:'.opendistro-ism-config',prirep:'r',state:'UNASSIGNED'},{index:'dmarc_aggregate-2026.09',prirep:'p',state:'STARTED'}],settings);
  assert.strictEqual(shards.total,2);
  assert.strictEqual(shards.all_replicas,true);
  assert.strictEqual(shards.affected_report_shards,0);
  assert.strictEqual(shards.groups.find(group=>group.category==='OpenSearch security audit logs').unassigned_shards,1);
  process.env.DEMO_MODE='true';const status=await app.refresh();assert.strictEqual(status.domains.length,1);assert.ok(status.summary.critical>0);assert.strictEqual(status.version,require('../package.json').version);assert.strictEqual(status.domains[0].mail_profile.provider,'self_hosted');
  assert.strictEqual(require('../package.json').version,'2.0.0');
  const page=fs.readFileSync('public/index.html','utf8'),client=fs.readFileSync('public/app.js','utf8'),styles=fs.readFileSync('public/settings.css','utf8'),icon=fs.readFileSync('public/mailposture.svg','utf8'),standalone=fs.readFileSync('compose.standalone.yml','utf8'),dockerfile=fs.readFileSync('Dockerfile','utf8'),smtpSource=fs.readFileSync('smtp.js','utf8');
  assert.match(page,/MailPosture/);
  assert.match(page,/id="dashboard-view"/);
  assert.match(page,/id="settings-view"/);
  assert.match(page,/id="system-status-view"/);
  assert.match(page,/id="system-log"/);
  assert.match(page,/id="log-service"/);
  assert.match(page,/id="service-log"/);
  assert.match(page,/id="service-log-service"/);
  assert.match(page,/v2\.0\.0/);
  assert.match(page,/Mail Security Dashboard/);
  assert.doesNotMatch(page,/DMARC authentication and SMTP TLS delivery results for the selected history window/);
  assert.match(page,/id="domain-menu-button"/);
  assert.match(page,/id="domain-menu-list"/);
  assert.match(page,/id="system-status-indicator"/);
  assert.match(page,/name="domain-sort" value="priority"/);
  assert.match(page,/name="domain-sort" value="alphabetical"/);
  assert.ok(page.indexOf('domain-attention-heading') < page.indexOf('id="attention"'));
  assert.match(page,/Event history/);
  assert.match(page,/id="bimi-ignore-mode"/);
  assert.match(page,/id="bimi-ignore-months"/);
  assert.match(page,/id="bimi-no-logo-ignore-mode"/);
  assert.match(page,/id="bimi-no-logo-ignore-months"/);
  assert.match(page,/id="smtp-probe-hostname"/);
  assert.match(page,/id="smtp-hosting-type"/);
  assert.match(page,/id="smtp-provider"/);
  assert.match(page,/Kerio Connect/);
  assert.match(page,/Hover Mail/);
  assert.match(page,/id="smtp-relay-context"/);
  assert.match(page,/IP and domain reputation/);
  assert.match(page,/Observed email traffic/);
  assert.ok(page.indexOf('id="attention"') < page.indexOf('class="matrix"'));
  assert.ok(page.indexOf('class="matrix"') < page.indexOf('id="report-center"'));
  assert.match(page,/SMTP service/);
  assert.match(page,/they never send DATA or message content/);
  assert.match(page,/href="\/status"/);
  assert.match(page,/dashboard-icon/);
  assert.match(page,/monitored-domains-icon/);
  assert.match(page,/system-status-icon/);
  assert.match(page,/run-checks-icon/);
  assert.match(page,/settings-icon/);
  assert.match(page,/id="organization-reports"/);
  assert.match(page,/id="domain-reports"/);
  assert.match(page,/id="report-source"/);
  assert.match(page,/id="mailbox-enabled"/);
  assert.match(page,/id="snapshots-enabled"/);
  assert.match(page,/role="tablist"/);
  assert.match(page,/data-settings-tab="parsedmarc"/);
  assert.match(page,/domains-icon/);
  assert.match(page,/appearance-icon/);
  assert.match(page,/opensearch-icon/);
  assert.match(page,/parsedmarc-icon/);
  assert.match(page,/id="pm-delete-smtp-tls"/);
  assert.match(page,/Archive\/SMTP-TLS/);
  assert.match(page,/id="help-view"/);
  assert.match(page,/id="domain-dialog"/);
  assert.match(page,/name="theme" value="system"/);
  assert.match(page,/aria-label="Settings"/);
  assert.match(page,/id="version"/);
  assert.match(client,/card-context/);
  assert.match(client,/renderDashboard/);
  assert.match(client,/renderSettingsDomains/);
  assert.match(client,/organizationReports/);
  assert.match(client,/reportingOrganizationsCard/);
  assert.match(client,/Individual DMARC failure reports \(RUF\)/);
  assert.match(client,/api\/system-logs/);
  assert.match(client,/api\/service-logs/);
  assert.match(client,/sourceList/);
  assert.match(client,/Reporter name not provided/);
  assert.match(client,/Scope:/);
  assert.match(client,/api\/bimi-logo/);
  assert.match(client,/bimi_exceptions/);
  assert.match(client,/bimiExceptionDirty/);
  assert.match(client,/dmarcReportersCard/);
  assert.match(client,/passed_dkim_aligned_rate/);
  assert.match(client,/hasFailures/);
  const detailLayout=client.slice(client.indexOf('function detailCards'),client.indexOf('function organizationReports'));
  for(const [before,after] of [['report-dmarc','report-smtp-tls'],['report-smtp-tls','report-dmarc-sources'],['report-dmarc-sources','report-smtp-tls-organizations'],['report-smtp-tls-organizations','report-dmarc-failure'],['report-dmarc-failure','report-smtp-tls-failures'],['report-smtp-tls-failures','report-dmarc-reporters']]) assert.ok(detailLayout.indexOf(before)<detailLayout.indexOf(after),`${before} must appear before ${after}`);
  assert.match(client,/ignored: 'Ignored'/);
  assert.match(client,/smtpDiagnosticsCard/);
  assert.match(client,/report-smtp-diagnostics/);
  assert.match(client,/certificate-days/);
  assert.match(client,/issue-status/);
  assert.match(client,/data-report-target/);
  assert.match(client,/selectSettingsTab/);
  assert.match(client,/renderDomainMenu/);
  assert.match(client,/mailposture-domain-sort/);
  assert.match(client,/MX endpoint results/);
  assert.match(client,/issue\$\{domain\.counts\.critical === 1 \? ' needs' : 's need'\}/);
  assert.ok(fs.existsSync('compose.standalone.yml'));
  assert.match(standalone,/ghcr\.io\/domainaware\/parsedmarc/);
  assert.match(standalone,/MAILPOSTURE_SETTINGS_PATH/);
  assert.match(standalone,/OPENSEARCH_DATA_PATH/);
  assert.match(standalone,/OPENSEARCH_SNAPSHOT_PATH/);
  assert.match(standalone,/type: bind/);
  assert.match(standalone,/target: \/etc\/parsedmarc\n\s+read_only: true/);
  assert.doesNotMatch(standalone,/target: \/etc\/parsedmarc:ro/);
  assert.match(standalone,/reloading parsedmarc/);
  assert.match(standalone,/parsedmarc_status/);
  assert.match(standalone,/write_status running/);
  assert.match(standalone,/SERVICE_LOGS_ENABLED: "true"/);
  assert.match(standalone,/opensearch_logs/);
  assert.match(standalone,/target: \/logs\/opensearch/);
  assert.match(standalone,/log_file="\/run\/mailposture\/parsedmarc\.log"/);
  assert.match(standalone,/wait_for_status=yellow/);
  assert.match(standalone,/timed_out/);
  assert.match(dockerfile,/smtp\.js/);
  assert.match(dockerfile,/dns-security\.js/);
  assert.match(smtpSource,/RCPT TO:<probe@example\.net>/);
  assert.doesNotMatch(smtpSource,/command\(['"]DATA/);
  assert.match(smtpSource,/policyBlock/);
  assert.ok(smtpSource.indexOf("reader.command('STARTTLS')") < smtpSource.indexOf("reader.command('MAIL FROM:<probe@example.com>')"));
  assert.match(styles,/#0c71c3/i);
  assert.match(styles,/monitored-domains\.svg/);
  assert.match(styles,/appearance\.svg/);
  assert.match(styles,/opensearch\.svg/);
  assert.match(styles,/parsedmarc\.svg/);
  assert.match(styles,/dashboard\.svg/);
  assert.match(styles,/run-checks\.svg/);
  assert.match(styles,/settings\.svg/);
  assert.match(styles,/status\.svg/);
  assert.match(styles,/system-status\.svg/);
  assert.match(styles,/\.domain-menu-list/);
  assert.match(styles,/\.score-watermark/);
  assert.match(styles,/#system-status-indicator/);
  assert.match(styles,/flex-direction:column-reverse/);
  assert.match(styles,/system-warning \.system-status-icon\{color:var\(--review-text\)\}/);
  assert.match(styles,/\.system-log/);
  assert.match(styles,/\.service-log/);
  assert.match(styles,/\.index-patterns/);
  assert.match(styles,/\.state\.ignored/);
  assert.match(styles,/--review:#ffd60a/i);
  assert.match(icon,/<svg/);
  assert.match(icon,/check mark/i);
  assert.match(icon,/#0C71C3/);
  for(const iconFile of ['appearance.svg','dashboard.svg','monitored-domains.svg','opensearch.svg','parsedmarc.svg','run-checks.svg','settings.svg','status.svg','system-status.svg']) assert.ok(fs.existsSync(`public/${iconFile}`));
  console.log('All MailPosture checks passed.');
}
run().catch(e=>{console.error(e);process.exitCode=1});
